### PR TITLE
Check sequences timestamp against POE SC lastTimestamp

### LINKED ISSUE #936: Sequencer fails to send sequence
While running the E2E test `Test1000EthTransfer` I faced this error:

```
2022-07-26T07:49:44Z	ERROR	sequencer/sequencer.go:361	failed to estimate gas for sequence batches, err: execution reverted: ProofOfEfficiency::sequenceBatches: Timestamp must be inside range%!(EXTRA string=
/src/log/log.go:106 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:164 github.com/0xPolygonHermez/zkevm-node/log.Errorf()
/src/sequencer/sequencer.go:361 github.com/0xPolygonHermez/zkevm-node/sequencer.(*Sequencer).shouldSendSequences()
/src/sequencer/sequencer.go:190 github.com/0xPolygonHermez/zkevm-node/sequencer.(*Sequencer).tryToProcessTx()
/src/sequencer/sequencer.go:130 github.com/0xPolygonHermez/zkevm-node/sequencer.(*Sequencer).Start()
```

### PR DESCRIPTION
**Pull request by ToniRamirezM**
Closes #936 

### What does this PR do?

Checks sequences timestamp against POE SC lastTimestamp variable to ensure it is valid.
Also updates the L1 container in the docker-compose file to a new images that forges blocks every second.

### Reviewers

Main reviewers:

- @arnaubennassar 
- @Mikelle 
- @fgimenez

### CODE REVIEW

File: sequencer/sequencer.go [hunk 1]
```diff
@@ -358,6 +359,26 @@ func (s *Sequencer) shouldSendSequences(ctx context.Context) (bool, bool) {
 	}
 
 	if err != nil {
+		// while estimating gas a new block is not created and the POE SC may return
+		// an error regarding timestamp verification, this must handled
```
Comment (fgimenez) [inline sequencer/sequencer.go:363]:
```suggestion
		// an error regarding timestamp verification, this must be handled
```

File: sequencer/sequencer.go [hunk 2]
```diff
@@ -358,6 +359,26 @@ func (s *Sequencer) shouldSendSequences(ctx context.Context) (bool, bool) {
...
+		if strings.Contains(err.Error(), errTimestampMustBeInsideRange) {
+			// query the sc about the value of its lastTimestamp variable
+			lastTimestamp, err := s.etherman.GetLastTimestamp()
+			if err != nil {
+				log.Errorf("failed to estimate gas for sequence batches, err: %v", err)
```
Comment (fgimenez) [inline sequencer/sequencer.go:368]:
```suggestion
				log.Errorf("failed to query last timestamp from SC, err: %v", err)
```

File: sequencer/sequencer.go [hunk 3]
```diff
@@ -358,6 +359,26 @@ func (s *Sequencer) shouldSendSequences(ctx context.Context) (bool, bool) {
...
+				return false, false
+			}
+			// check POE SC lastTimestamp against sequences' one
+			for _, seq := range s.closedSequences {
```
Comment (fgimenez) [inline sequencer/sequencer.go:372]: I don't understand, can't it be possible that old closed sequences have a timestamp lower than the current last timestamp from the SC?

Comment (arnaubennassar) [reply sequencer/sequencer.go:372]: As the sequencer chooses timestamps, it could happen. It shouldn't, but it could. And the SC has a require that checks that, so if this ever happens, the SC won't accept the sequence.

File: sequencer/sequencer.go [hunk 4]
```diff
@@ -358,6 +359,26 @@ func (s *Sequencer) shouldSendSequences(ctx context.Context) (bool, bool) {
...
+				if seq.Timestamp < int64(lastTimestamp) {
+					panic("sequence timestamp is < POE SC lastTimestamp")
+				}
```
Comment (arnaubennassar) [inline sequencer/sequencer.go:375]: update the lasTimestamp to use the current sequence timestamp, to better reflect the SC require

```suggestion
				}
				lastTimeStamp = seq.Timestamp
```

File: sequencer/sequencer.go [hunk 5]
```diff
@@ -358,6 +359,26 @@ func (s *Sequencer) shouldSendSequences(ctx context.Context) (bool, bool) {
...
+			}
+
+			log.Debug("block.timestamp is greater than seq.Timestamp. A new block must be forged.")
```
Comment (arnaubennassar) [inline sequencer/sequencer.go:378]:
```suggestion
			log.Debug("block.timestamp is greater than seq.Timestamp. A new L1 block must be mined before the gas can be estimated.")
```

**Review by arnaubennassar — CHANGES_REQUESTED** [review]

File: sequencer/sequencer.go (hunk 4 above)
Comment (ToniRamirezM) [reply sequencer/sequencer.go:375]: I don't get this. lastTimestamp is not used later in the code.

**Review by fgimenez — APPROVED** [review]

File: sequencer/sequencer.go (hunk 4 above)
Comment (arnaubennassar) [reply sequencer/sequencer.go:375]: The idea is that in the next iteration, `if seq.Timestamp < int64(lastTimestamp) {` lastTimeStamp should be the timpestamp of the previous item in the sequences

**Review by arnaubennassar — CHANGES_REQUESTED** [review]

File: sequencer/sequencer.go (hunk 4 above)
Comment (ToniRamirezM) [reply sequencer/sequencer.go:375]: Ok, now I see. During SC execution the lastTimestamp will be updated with the previous (known to be correct) one.

**Review by arnaubennassar — APPROVED** [review]

File: sequencer/sequencer.go [hunk 6]
```diff
@@ -358,6 +359,27 @@ func (s *Sequencer) shouldSendSequences(ctx context.Context) (bool, bool) {
...
+			// query the sc about the value of its lastTimestamp variable
+			lastTimestamp, err := s.etherman.GetLastTimestamp()
+			if err != nil {
+				log.Errorf("failed to query last timestamp from SC, err: %v", err)
+				return false, false
+			}
+			// check POE SC lastTimestamp against sequences' one
+			for _, seq := range s.closedSequences {
+				if seq.Timestamp < int64(lastTimestamp) {
+					panic("sequence timestamp is < POE SC lastTimestamp")
```
Comment (Mikelle) [inline sequencer/sequencer.go:374]:
```suggestion
					log.Fatalf("sequence timestamp %d is < POE SC lastTimestamp %d", seq.Timestamp, lastTimestamp)
```

**Review by Mikelle — APPROVED** [review]
