### PR TITLE
Synchronizer L1 parallel: fix stuck due error on request

### LINKED ISSUE #2578: Synchronizer L1 parallel: fix stuck due error on request
# Rationale
When an request to L1 is failing persistently need to stop making new request

# Implementation
Limit pending of results

### PR DESCRIPTION
**Pull request by joanestebanr**
Closes #2578

### What does this PR do?
Limit number of pending results to serve to consumer

### Reviewers

Main reviewers:
@ARR552

### CODE REVIEW

File: synchronizer/l1_syncstatus.go [hunk 1]
```diff
@@ -92,6 +92,17 @@ func (s *syncStatus) isNodeFullySynchronizedWithL1() bool {
 	return false
 }
 
+func (s *syncStatus) getNextRangeOnlyRetries() *blockRange {
+	s.mutex.Lock()
+	defer s.mutex.Unlock()
+	// Check if there are any range that need to be retried
+	blockRangeToRetry, err := s.errorRanges.getFirstBlockRange()
```
Comment (ARR552) [inline synchronizer/l1_syncstatus.go:103]: Why this function doesn't use the Unsafe?

File: synchronizer/l1_rollup_info_producer.go [hunk 2]
```diff
@@ -327,24 +331,41 @@ func (l *l1RollupInfoProducer) onNewLastBlock(lastBlock uint64, launchWork bool)
...
+func (l *l1RollupInfoProducer) canISendNewRequestsUnsafe() (bool, string) {
+	queued := l.filterToSendOrdererResultsToConsumer.numItemBlockedInQueue()
+	inChannel := len(l.outgoingChannel)
+	maximum := cap(l.outgoingChannel)
+	msg := fmt.Sprintf("inFilter:%d + inChannel:%d > maximum:%d?", queued, inChannel, maximum)
+	if queued+inChannel > maximum {
+		msg = msg + " ==> only allow retries"
+		return false, msg
+	}
+	msg = msg + " ==> allow new req"
```
Comment (ARR552) [inline synchronizer/l1_rollup_info_producer.go:343]: Why don't you just log the message here instead of returning the message and log it in other function??

Comment (joanestebanr) [reply synchronizer/l1_rollup_info_producer.go:343]: It's to have all info in the same log, a long the function accumulate the logs of this execution and at end it emmit only 1 info trace

File: synchronizer/l1_syncstatus.go (hunk 1 above)
Comment (joanestebanr) [reply synchronizer/l1_syncstatus.go:103]: Yes, you're right!, I'm duplicating code. I'll fix it

**Review by ARR552 — APPROVED** [review]
