### PR TITLE
PoC: retrying connection to executor

### LINKED ISSUE #1339: Stabilize tests: retry connection to executor
Sometimes GitHub Actions tests fail due to connection failure to executor despite the service being up:

```
2022-10-27T10:52:07Z	INFO	executor/client.go:25	trying to connect to executor: 127.0.0.1:50071
2022-10-27T10:54:07Z	FATAL	executor/client.go:28	fail to dial: context deadline exceeded%!(EXTRA string=
/home/runner/work/zkevm-node/zkevm-node/log/log.go:106 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/home/runner/work/zkevm-node/zkevm-node/log/log.go:158 github.com/0xPolygonHermez/zkevm-node/log.Fatalf()
/home/runner/work/zkevm-node/zkevm-node/state/runtime/executor/client.go:28 github.com/0xPolygonHermez/zkevm-node/state/runtime/executor.NewExecutorClient()
/home/runner/work/zkevm-node/zkevm-node/test/operations/manager.go:297 github.com/0xPolygonHermez/zkevm-node/test/operations.initState()
/home/runner/work/zkevm-node/zkevm-node/test/operations/manager.go:93 github.com/0xPolygonHermez/zkevm-node/test/operations.NewManager()
/home/runner/work/zkevm-node/zkevm-node/ci/e2e-group3/sc_test.go:33 github.com/0xPolygonHermez/zkevm-node/ci/e2e-group3.TestEmitLog2()
/opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 testing.tRunner()
)
FAIL	github.com/0xPolygonHermez/zkevm-node/ci/e2e-group3	127.601s
```

Code should retry multiple times, and timeout should be shorter.

### PR DESCRIPTION
**Pull request by KonradIT**
Closes #1339.

### What does this PR do?

Retries connection to executor 5 times before throwing fatal error

### Reviewers

Main reviewers:

- @ARR552 
- @ToniRamirezM 

Codeowner reviewers:

### CODE REVIEW

File: state/runtime/executor/client.go [hunk 1]
```diff
@@ -20,15 +20,28 @@ func NewExecutorClient(ctx context.Context, c Config) (pb.ExecutorServiceClient,
...
 	}
 	const maxWaitSeconds = 120
+	const maxRetries = 5
 	ctx, cancel := context.WithTimeout(ctx, maxWaitSeconds*time.Second)
 
-	log.Infof("trying to connect to executor: %v", c.URI)
-	executorConn, err := grpc.DialContext(ctx, c.URI, opts...)
-	if err != nil {
-		log.Fatalf("fail to dial: %v", err)
+	connections := 0
```
Comment (ToniRamirezM) [inline state/runtime/executor/client.go:26]: Call this variable "tries" or  "connectionRetries"

**Review by ToniRamirezM — APPROVED** [review]
