### PR TITLE
fix memory reading for custom tracers when memory is smaller than stack values

### LINKED ISSUE #2139: custom tracer fails to generate tracer when memory is smaller than stack values

### LINKED ISSUE #2141: CallTracer Bug: Gas used in is not display properly
#### System information

zkEVM Node version: `v0.1.1-RC2`

#### Expected behaviour
gasUsed is display properly. The gas used should indicate how much gas was wasted on the call,
#### Actual behaviour
Is returning "mock values" like `0x1` `0x2` ...

I will present to compare 2 traces of claimAsset which claim ethers in both networks, Goerli and zkEVM: 
Remember the behaviour is not Exactly the same bc are different transactions, but the example is just to illustrate how it should look.
Goerli txHash: `0x4311b1c644ddfa5031417dc0b14d1d8aaeb6069549d389edeeaff28cd962b01b`
zkEVM txHash: `0xf998f44e502b7afe86b82d061c789e2fbc05e7e9e1b913b0a77356d0e9615ef8`

Goerli:
```
{
 "from": "0x443bb8db5a8e3dd6e20d2357653eee334e828e45",
 "gas": "0xca8e",
 "gasUsed": "0x161f9",
 "to": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
 "input": "0x2cffd02e0000000000000000000000000000000000000000000000000000000000000000ad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5b4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d3021ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba852b59081fce48057b966b0edbab4ca42ff01919853b23b9aebaa4ad876f0f4bdef3ea80bc7ce990d273e148a10c587c067037a4a87a68f15bfcfd9eafb7744511887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968d1832ec9686cbcf6232e936ada92446a6ff0698fab000ec821d054a22ca30163d183d6a4e233695d49d04eb6e51d9b25819dddbf2c8a80deda4fd9f0a88fed09c2c5eed50df07195f9f9450c51a55b5add2a0ccbfa92002c88f87dc13d7cf5b9f9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a5f8b13a49e282f609c317a833fb8d976d11517c571d1221a265d25af778ecf8923490c6ceeb450aecdc82e28293031d10c7d73bf85e57bf041a97360aa2c5d99cc1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7bce9f4e8618b6bd2f4132ce798cdc7a60e7e1460a7299e3c6342a579626d22733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a900000000000000000000000000000000000000000000000000000000000003b05db1b7fe81d72b349d12ea10505d733148ef08198286785632765ea678ed91ba837074ddb3d0f6b7751e702480a96dde2da22150f8604072c0b733b535ee9fd6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000443bb8db5a8e3dd6e20d2357653eee334e828e4500000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000000",
 "calls": [
  {
   "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
   "gas": "0xaad8",
   "gasUsed": "0xaad3",
   "to": "0x15d50fa9623bdd20603e9e2c48e470636c8633c2",
   "input": "0x2cffd02e0000000000000000000000000000000000000000000000000000000000000000ad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5b4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d3021ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba852b59081fce48057b966b0edbab4ca42ff01919853b23b9aebaa4ad876f0f4bdef3ea80bc7ce990d273e148a10c587c067037a4a87a68f15bfcfd9eafb7744511887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968d1832ec9686cbcf6232e936ada92446a6ff0698fab000ec821d054a22ca30163d183d6a4e233695d49d04eb6e51d9b25819dddbf2c8a80deda4fd9f0a88fed09c2c5eed50df07195f9f9450c51a55b5add2a0ccbfa92002c88f87dc13d7cf5b9f9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a5f8b13a49e282f609c317a833fb8d976d11517c571d1221a265d25af778ecf8923490c6ceeb450aecdc82e28293031d10c7d73bf85e57bf041a97360aa2c5d99cc1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7bce9f4e8618b6bd2f4132ce798cdc7a60e7e1460a7299e3c6342a579626d22733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a900000000000000000000000000000000000000000000000000000000000003b05db1b7fe81d72b349d12ea10505d733148ef08198286785632765ea678ed91ba837074ddb3d0f6b7751e702480a96dde2da22150f8604072c0b733b535ee9fd6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000443bb8db5a8e3dd6e20d2357653eee334e828e4500000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000000",
   "calls": [
    {
     "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
     "gas": "0x7c11",
     "gasUsed": "0x2629",
     "to": "0x6407cf296a27b38fd29c401518504d388f1dfb3d",
     "input": "0x257b3632c72c75b16925742d5826852b3b078925f432337ba29933f118519b92d3aacd43",
     "output": "0x00000000000000000000000000000000000000000000000000000000647463c0",
     "calls": [
      {
       "from": "0x6407cf296a27b38fd29c401518504d388f1dfb3d",
       "gas": "0x5e25",
       "gasUsed": "0x992",
       "to": "0xefaf1504d7ff3ebb828d6f1b6776cf9e2a3d67b7",
       "input": "0x257b3632c72c75b16925742d5826852b3b078925f432337ba29933f118519b92d3aacd43",
       "output": "0x00000000000000000000000000000000000000000000000000000000647463c0",
       "type": "DELEGATECALL"
      }
     ],
     "value": "0x0",
     "type": "CALL"
    },
    {
     "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
     "gas": "0x8fc",
     "gasUsed": "0x0",
     "to": "0x443bb8db5a8e3dd6e20d2357653eee334e828e45",
     "input": "0x",
     "value": "0x38d7ea4c68000",
     "type": "CALL"
    }
   ],
   "type": "DELEGATECALL"
  }
 ],
 "value": "0x0",
 "type": "CALL"
}
```

zkEVM
```
{
 "from": "0x4ca25c4e560fb5adc3ff43eb0ad82ee0cd84aace",
 "gas": "0x1851a",
 "gasUsed": "0x16bab",
 "to": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
 "input": "0x2cffd02e0000000000000000000000000000000000000000000000000000000000000000088bb0a78546eba1f7798d0faa0df5fae526a7e65fa676bfaff49adb018f81b8b4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d3021ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85ecf565ca71bd78388f5b70c13c81e689d459ed5053c83248da090c3e358267510eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2dc2240670224cff6c6e5ca7eaa7d998070f128e9e90b1941d4896e271bfbbf3592230b20cd3f046dfe5c2f1fe4ede06298b790b4eda0d8231cb84273297b084639867cc5f7f196b93bae1e27e6320742445d290f2263827498b54fec539f756afcefad4e508c098b9a7e1d8feb19955fb02ba9675585078710969d3440f5054e0f9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a518a1e8209131b5a06bca9b2c58155b82514ec30d11cd5b1e97fcd09a7f9ca3923490c6ceeb450aecdc82e28293031d10c7d73bf85e57bf041a97360aa2c5d99cc1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7bce9f4e8618b6bd2f4132ce798cdc7a60e7e1460a7299e3c6342a579626d22733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a900000000000000000000000000000000000000000000000000000000000008d25db1b7fe81d72b349d12ea10505d733148ef08198286785632765ea678ed91ba52480ec1e0a76396429e5ee900b65a133c74195a02f62f3c37712024ee09d983000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000443bb8db5a8e3dd6e20d2357653eee334e828e45000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000000",
 "calls": [
  {
   "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
   "gas": "0xd836",
   "gasUsed": "0x3",
   "to": "0x15d50fa9623bdd20603e9e2c48e470636c8633c2",
   "input": "0x2cffd02e0000000000000000000000000000000000000000000000000000000000000000088bb0a78546eba1f7798d0faa0df5fae526a7e65fa676bfaff49adb018f81b8b4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d3021ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85ecf565ca71bd78388f5b70c13c81e689d459ed5053c83248da090c3e358267510eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2dc2240670224cff6c6e5ca7eaa7d998070f128e9e90b1941d4896e271bfbbf3592230b20cd3f046dfe5c2f1fe4ede06298b790b4eda0d8231cb84273297b084639867cc5f7f196b93bae1e27e6320742445d290f2263827498b54fec539f756afcefad4e508c098b9a7e1d8feb19955fb02ba9675585078710969d3440f5054e0f9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a518a1e8209131b5a06bca9b2c58155b82514ec30d11cd5b1e97fcd09a7f9ca3923490c6ceeb450aecdc82e28293031d10c7d73bf85e57bf041a97360aa2c5d99cc1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7bce9f4e8618b6bd2f4132ce798cdc7a60e7e1460a7299e3c6342a579626d22733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a900000000000000000000000000000000000000000000000000000000000008d25db1b7fe81d72b349d12ea10505d733148ef08198286785632765ea678ed91ba52480ec1e0a76396429e5ee900b65a133c74195a02f62f3c37712024ee09d983000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000443bb8db5a8e3dd6e20d2357653eee334e828e45000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000000",
   "calls": [
    {
     "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
     "gas": "0xa82f",
     "gasUsed": "0x3",
     "to": "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa",
     "input": "0x257b3632bcf469a2ddff3555b769d31ac980d15b672645e8cd5de5a34c197553c330d9ab",
     "output": "0x000000000000000000000000000000000000000000000000000000006474596a",
     "calls": [
      {
       "from": "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa",
       "gas": "0x8949",
       "gasUsed": "0x2",
       "to": "0xe641334b752d435a5133f64c6dbab34431a9b9dc",
       "input": "0x257b3632bcf469a2ddff3555b769d31ac980d15b672645e8cd5de5a34c197553c330d9ab",
       "output": "0x000000000000000000000000000000000000000000000000000000006474596a",
       "value": "0x0",
       "type": "DELEGATECALL"
      }
     ],
     "value": "0x0",
     "type": "CALL"
    }
   ],
   "value": "0x0",
   "type": "DELEGATECALL"
  },
  {
   "from": "0x15d50fa9623bdd20603e9e2c48e470636c8633c2",
   "gas": "0x43a8",
   "gasUsed": "0x3",
   "to": "0x443bb8db5a8e3dd6e20d2357653eee334e828e45",
   "input": "0x",
   "value": "0x0",
   "type": "CALL"
  }
 ],
 "value": "0x0",
 "type": "CALL"
}
```

### LINKED ISSUE #2142: CallTracer Bug: Inside the delegateCall the ether value transfer is not showed properly, also the from is incorrect
#### System information

zkEVM Node version: `v0.1.1-RC2`

#### Expected behaviour
It should show properly the value ether transferred ( which is related to the last call) 
The `from` should be the contract that is executing the logic, and NOT the contract that we are reading the bytecode in the DelegateCall
#### Actual behaviour
It shows `0` instead
The `from` that is displayed in the call is the contract that we are reading the bytecode

Notice i add in the traces below `// THIS IS THE MAIN POINT OF THE ISSUE ///` comment to actual point to the current isssue call

I will present to compare 2 traces of claimAsset which claim ethers in both networks, Goerli and zkEVM: 
Remember the behaviour is not Exactly the same bc are different transactions, but the example is just to illustrate how it should look.
Goerli txHash: `0x4311b1c644ddfa5031417dc0b14d1d8aaeb6069549d389edeeaff28cd962b01b`
zkEVM txHash: `0xf998f44e502b7afe86b82d061c789e2fbc05e7e9e1b913b0a77356d0e9615ef8`

Goerli:
```
{
 "from": "0x443bb8db5a8e3dd6e20d2357653eee334e828e45",
 "gas": "0xca8e",
 "gasUsed": "0x161f9",
 "to": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
 "input": "0x2cffd02e0000000000000000000000000000000000000000000000000000000000000000ad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5b4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d3021ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba852b59081fce48057b966b0edbab4ca42ff01919853b23b9aebaa4ad876f0f4bdef3ea80bc7ce990d273e148a10c587c067037a4a87a68f15bfcfd9eafb7744511887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968d1832ec9686cbcf6232e936ada92446a6ff0698fab000ec821d054a22ca30163d183d6a4e233695d49d04eb6e51d9b25819dddbf2c8a80deda4fd9f0a88fed09c2c5eed50df07195f9f9450c51a55b5add2a0ccbfa92002c88f87dc13d7cf5b9f9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a5f8b13a49e282f609c317a833fb8d976d11517c571d1221a265d25af778ecf8923490c6ceeb450aecdc82e28293031d10c7d73bf85e57bf041a97360aa2c5d99cc1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7bce9f4e8618b6bd2f4132ce798cdc7a60e7e1460a7299e3c6342a579626d22733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a900000000000000000000000000000000000000000000000000000000000003b05db1b7fe81d72b349d12ea10505d733148ef08198286785632765ea678ed91ba837074ddb3d0f6b7751e702480a96dde2da22150f8604072c0b733b535ee9fd6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000443bb8db5a8e3dd6e20d2357653eee334e828e4500000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000000",
 "calls": [
  {
   "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
   "gas": "0xaad8",
   "gasUsed": "0xaad3",
   "to": "0x15d50fa9623bdd20603e9e2c48e470636c8633c2",
   "input": "0x2cffd02e0000000000000000000000000000000000000000000000000000000000000000ad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5b4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d3021ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba852b59081fce48057b966b0edbab4ca42ff01919853b23b9aebaa4ad876f0f4bdef3ea80bc7ce990d273e148a10c587c067037a4a87a68f15bfcfd9eafb7744511887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968d1832ec9686cbcf6232e936ada92446a6ff0698fab000ec821d054a22ca30163d183d6a4e233695d49d04eb6e51d9b25819dddbf2c8a80deda4fd9f0a88fed09c2c5eed50df07195f9f9450c51a55b5add2a0ccbfa92002c88f87dc13d7cf5b9f9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a5f8b13a49e282f609c317a833fb8d976d11517c571d1221a265d25af778ecf8923490c6ceeb450aecdc82e28293031d10c7d73bf85e57bf041a97360aa2c5d99cc1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7bce9f4e8618b6bd2f4132ce798cdc7a60e7e1460a7299e3c6342a579626d22733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a900000000000000000000000000000000000000000000000000000000000003b05db1b7fe81d72b349d12ea10505d733148ef08198286785632765ea678ed91ba837074ddb3d0f6b7751e702480a96dde2da22150f8604072c0b733b535ee9fd6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000443bb8db5a8e3dd6e20d2357653eee334e828e4500000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000000",
   "calls": [
    {
     "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
     "gas": "0x7c11",
     "gasUsed": "0x2629",
     "to": "0x6407cf296a27b38fd29c401518504d388f1dfb3d",
     "input": "0x257b3632c72c75b16925742d5826852b3b078925f432337ba29933f118519b92d3aacd43",
     "output": "0x00000000000000000000000000000000000000000000000000000000647463c0",
     "calls": [
      {
       "from": "0x6407cf296a27b38fd29c401518504d388f1dfb3d",
       "gas": "0x5e25",
       "gasUsed": "0x992",
       "to": "0xefaf1504d7ff3ebb828d6f1b6776cf9e2a3d67b7",
       "input": "0x257b3632c72c75b16925742d5826852b3b078925f432337ba29933f118519b92d3aacd43",
       "output": "0x00000000000000000000000000000000000000000000000000000000647463c0",
       "type": "DELEGATECALL"
      }
     ],
     "value": "0x0",
     "type": "CALL"
    },
// THIS IS THE MAIN POINT OF THE ISSUE ///
    {
     "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
     "gas": "0x8fc",
     "gasUsed": "0x0",
     "to": "0x443bb8db5a8e3dd6e20d2357653eee334e828e45",
     "input": "0x",
     "value": "0x38d7ea4c68000",
     "type": "CALL"
    }
   ],
   "type": "DELEGATECALL"
  }
 ],
 "value": "0x0",
 "type": "CALL"
}
```

zkEVM
```
{
 "from": "0x4ca25c4e560fb5adc3ff43eb0ad82ee0cd84aace",
 "gas": "0x1851a",
 "gasUsed": "0x16bab",
 "to": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
 "input": "0x2cffd02e0000000000000000000000000000000000000000000000000000000000000000088bb0a78546eba1f7798d0faa0df5fae526a7e65fa676bfaff49adb018f81b8b4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d3021ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85ecf565ca71bd78388f5b70c13c81e689d459ed5053c83248da090c3e358267510eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2dc2240670224cff6c6e5ca7eaa7d998070f128e9e90b1941d4896e271bfbbf3592230b20cd3f046dfe5c2f1fe4ede06298b790b4eda0d8231cb84273297b084639867cc5f7f196b93bae1e27e6320742445d290f2263827498b54fec539f756afcefad4e508c098b9a7e1d8feb19955fb02ba9675585078710969d3440f5054e0f9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a518a1e8209131b5a06bca9b2c58155b82514ec30d11cd5b1e97fcd09a7f9ca3923490c6ceeb450aecdc82e28293031d10c7d73bf85e57bf041a97360aa2c5d99cc1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7bce9f4e8618b6bd2f4132ce798cdc7a60e7e1460a7299e3c6342a579626d22733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a900000000000000000000000000000000000000000000000000000000000008d25db1b7fe81d72b349d12ea10505d733148ef08198286785632765ea678ed91ba52480ec1e0a76396429e5ee900b65a133c74195a02f62f3c37712024ee09d983000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000443bb8db5a8e3dd6e20d2357653eee334e828e45000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000000",
 "calls": [
  {
   "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
   "gas": "0xd836",
   "gasUsed": "0x3",
   "to": "0x15d50fa9623bdd20603e9e2c48e470636c8633c2",
   "input": "0x2cffd02e0000000000000000000000000000000000000000000000000000000000000000088bb0a78546eba1f7798d0faa0df5fae526a7e65fa676bfaff49adb018f81b8b4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d3021ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85ecf565ca71bd78388f5b70c13c81e689d459ed5053c83248da090c3e358267510eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2dc2240670224cff6c6e5ca7eaa7d998070f128e9e90b1941d4896e271bfbbf3592230b20cd3f046dfe5c2f1fe4ede06298b790b4eda0d8231cb84273297b084639867cc5f7f196b93bae1e27e6320742445d290f2263827498b54fec539f756afcefad4e508c098b9a7e1d8feb19955fb02ba9675585078710969d3440f5054e0f9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a518a1e8209131b5a06bca9b2c58155b82514ec30d11cd5b1e97fcd09a7f9ca3923490c6ceeb450aecdc82e28293031d10c7d73bf85e57bf041a97360aa2c5d99cc1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7bce9f4e8618b6bd2f4132ce798cdc7a60e7e1460a7299e3c6342a579626d22733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a900000000000000000000000000000000000000000000000000000000000008d25db1b7fe81d72b349d12ea10505d733148ef08198286785632765ea678ed91ba52480ec1e0a76396429e5ee900b65a133c74195a02f62f3c37712024ee09d983000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000443bb8db5a8e3dd6e20d2357653eee334e828e45000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000000",
   "calls": [
    {
     "from": "0xcfa773cc48fbde3ca4d24eecb19d224d697026b2",
     "gas": "0xa82f",
     "gasUsed": "0x3",
     "to": "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa",
     "input": "0x257b3632bcf469a2ddff3555b769d31ac980d15b672645e8cd5de5a34c197553c330d9ab",
     "output": "0x000000000000000000000000000000000000000000000000000000006474596a",
     "calls": [
      {
       "from": "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa",
       "gas": "0x8949",
       "gasUsed": "0x2",
       "to": "0xe641334b752d435a5133f64c6dbab34431a9b9dc",
       "input": "0x257b3632bcf469a2ddff3555b769d31ac980d15b672645e8cd5de5a34c197553c330d9ab",
       "output": "0x000000000000000000000000000000000000000000000000000000006474596a",
       "value": "0x0",
       "type": "DELEGATECALL"
      }
     ],
     "value": "0x0",
     "type": "CALL"
    }
   ],
   "value": "0x0",
   "type": "DELEGATECALL"
  },
// THIS IS THE MAIN POINT OF THE ISSUE ///
  {
   "from": "0x15d50fa9623bdd20603e9e2c48e470636c8633c2", // FROM SHOULD BE 0xcfa773cc48fbde3ca4d24eecb19d224d697026b2
   "gas": "0x43a8",
   "gasUsed": "0x3", 
   "to": "0x443bb8db5a8e3dd6e20d2357653eee334e828e45",
   "input": "0x",
   "value": "0x0", // VALUE SHOULD NOT BE 0
   "type": "CALL"
  }
 ],
 "value": "0x0",
 "type": "CALL"
}
```

### PR DESCRIPTION
**Pull request by tclemos**
Closes #2139.
Closes #2141.
Closes #2142.
Closes #2141.

### What does this PR do?

default tracer fixes:
- suppressed unnecessary STOP structure log provided by new executor version for internal transactions

custom tracer fixes:
- fix memory reading for custom tracers when memory is smaller than stack values
- fix how to handle revert opcodes for internal transactions
- fix how to handle consecutive calls with internal delegate calls

### Reviewers

Main reviewers:

@agnusmor 
@ToniRamirezM

### CODE REVIEW

File: state/transaction.go [hunk 1]
```diff
@@ -628,8 +628,21 @@ func (s *State) getPreCompiledCallAddressAndInput(step instrumentation.Step) (co
...
-		copy(input[0:argsSize], step.Memory[argsOffset:argsOffset+argsSize])
+
+		if argsOffset > uint64(len(step.Memory)) {
+			// when none of the bytes can be found in the memory
+			// do nothing to keep input as zeroes
+		} else if argsOffset+argsSize > uint64(len(step.Memory)) {
+			// when partial bytes are found in the memory
+			// copy just the bytes we have in memory and complement the rest with zeroes
+			copy(input[0:argsSize], step.Memory[argsOffset:argsOffset+uint64(len(step.Memory))-argsOffset])
+		} else {
```
Comment (invocamanman) [inline state/transaction.go:641]: Shouldn't be:
```
copy(input[0:argsSize], step.Memory[uint64(len(step.Memory))])
```
you are summing and subtracting `argsOffset`

File: state/transaction.go [hunk 2]
```diff
@@ -528,6 +528,12 @@ func (s *State) ParseTheTraceUsingTheTracer(evm *fakevm.FakeEVM, trace instrumen
 		// when a revert is detected, we stop the execution
 		if step.OpCode == "REVERT" {
 			stepError = fakevm.ErrExecutionReverted
+			// exit all contexts
+			if step.Depth > 1 {
+				for i := step.Depth; i > 1; i-- {
+					tracer.CaptureExit(step.ReturnData, gasCost.Uint64(), stepError)
+				}
```
Comment (invocamanman) [inline state/transaction.go:535]: I'm not sure about this one, why we need to exit all the contexts???
May happen that a context revert, but the previous one continues the execution correctly!

Comment (tclemos) [reply state/transaction.go]: Yes, I've created 2 new tests to validate it and fixed it.

File: state/transaction.go [hunk 3]
```diff
@@ -574,12 +573,16 @@ func (s *State) ParseTheTraceUsingTheTracer(evm *fakevm.FakeEVM, trace instrumen
 				}
 				tracer.CaptureExit(step.ReturnData, previousStepGasCost.Uint64(), previousError)
 			} else {
+				value := hex.DecodeBig(step.Contract.Value)
+				if previousStep.OpCode == "STATICCALL" {
+					value = nil
+				}
```
Comment (invocamanman) [inline state/transaction.go:579]: just review it but i think this is true also for delegateCalls ( in the callTracer traces)

Comment (tclemos) [reply state/transaction.go:579]: It's not that simple, we need to investigate this further

**Review by GloWE3 — DISMISSED** [review]

**Review by ToniRamirezM — APPROVED** [review]

**Review by Ameralameri — COMMENTED** [review]
Approv
