### PR TITLE
fix error check returned by the executor when debug tracing a block

### LINKED ISSUE #2589: debug_traceBlockByHash sometimes returns null
#### System information

zkEVM Node version: `v0.0.X-RCXX`
OS & Version: `Windows/Linux/OSX`
Commit hash : (if `develop`)
Network: `Mainnet/Testnet`

#### Expected behaviour
Hey Team, we have an important customer reporting an issue where the results of debug_trace_BlockByHash sometimes returns null while other times it randomly returns a result. The Block hash in question here is 0x17ce8630608bc0bc1cf6ba754350472eecffe1b9b48f25faa510675a587051ef
We don’t know if there are any other blocks with this issue as our customer must first get past this block.

#### Actual behaviour
Result must be consistent for all requests

#### Steps to reproduce the behaviour
```json
{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByHash",
    "params": [
        "0x17ce8630608bc0bc1cf6ba754350472eecffe1b9b48f25faa510675a587051ef",
        {
            "tracer": "callTracer",
            "timeout": "300s"
        }
    ],
    "id": 1
}
```

### PR DESCRIPTION
**Pull request by tclemos**
Closes #2589.

### What does this PR do?

fix error check returned by the executor when debug tracing a block

### Reviewers

Main reviewers:

@joanestebanr 
@ARR552

### CODE REVIEW

File: jsonrpc/endpoints_debug.go [hunk 1]
```diff
@@ -283,7 +283,7 @@ func (d *DebugEndpoints) buildTraceBlock(ctx context.Context, txs []*ethTypes.Tr
 	for _, tx := range txs {
 		traceTransaction, err := d.buildTraceTransaction(ctx, tx.Hash(), cfg, dbTx)
 		if err != nil {
-			errMsg := fmt.Sprintf("failed to get trace for transaction %v", tx.Hash().String())
+			errMsg := fmt.Sprintf("failed to get trace for transaction %v: %v", tx.Hash().String(), err.Error())
```
Comment (ARR552) [inline jsonrpc/endpoints_debug.go:286]:
```suggestion
			errMsg := fmt.Sprintf("failed to get trace for transaction %s: %s", tx.Hash().String(), err.Error())
```

File: jsonrpc/endpoints_debug.go [hunk 2]
```diff
@@ -318,8 +318,7 @@ func (d *DebugEndpoints) buildTraceTransaction(ctx context.Context, hash common.
 	if errors.Is(err, state.ErrNotFound) {
 		return RPCErrorResponse(types.DefaultErrorCode, "transaction not found", nil, false)
 	} else if err != nil {
-		const errorMessage = "failed to get trace"
-		log.Errorf("%v: %v", errorMessage, err)
+		errorMessage := fmt.Sprintf("failed to get trace: %v", err.Error())
```
Comment (ARR552) [inline jsonrpc/endpoints_debug.go:321]:
```suggestion
		errorMessage := fmt.Sprintf("failed to get trace: %s", err.Error())
```

**Review by ARR552 — CHANGES_REQUESTED** [review]

**Review by ARR552 — APPROVED** [review]
