### PR TITLE
Fix/#2263 gas used

### LINKED ISSUE #2263: Fix  div by 0 when GasUsed is 0

### PR DESCRIPTION
**Pull request by ARR552**
Closes #2263

### What does this PR do?

Fix div by 0 and fea2scalar

### Reviewers

- @agnusmor

### CODE REVIEW

**Review by Psykepro — APPROVED** [review]

File: pool/pool.go [hunk 1]
```diff
@@ -170,6 +170,25 @@ func (p *Pool) StoreTx(ctx context.Context, tx types.Transaction, ip string, isW
...
+		errors.Is(err, runtime.ErrBalanceMismatch) ||
+		errors.Is(err, runtime.ErrTos32) {
+		event := &event.Event{
+			ReceivedAt:  time.Now(),
+			IPAddress:   ip,
+			Source:      event.Source_Node,
+			Component:   event.Component_Pool,
+			Level:       event.Level_Critical,
+			EventID:     event.EventID_ExecutorError,
+			Description: tx.Hash().String(),
```
Comment (agnusmor) [inline pool/pool.go]: we must store in the field "Description" the error description to know if it was Fea2Scalar, BalanceMismatch or Tos32

File: sequencer/finalizer.go [hunk 2]
```diff
@@ -580,6 +581,37 @@ func (f *finalizer) processTransaction(ctx context.Context, tx *TxTracker) (errW
 	} else if tx != nil && err == nil && !processBatchResponse.IsRomLevelError && len(processBatchResponse.Responses) == 0 {
 		err = fmt.Errorf("executor returned no errors and no responses for tx: %s", tx.HashStr)
 		f.halt(ctx, err)
+	} else if tx != nil && processBatchResponse.ExecutorError == runtime.ErrBalanceMismatch ||
```
Comment (agnusmor) [inline sequencer/finalizer.go:584]: Reviewing again the code I think the correct place to check for these errors is in the handleProcessTransactionResult or handleProcessTransactionError function. We need to discuss/review this
