### PR TITLE
bugfix: adding deletion of invalid txs from pool db in the finalizer.

### LINKED ISSUE #1695: Add deletion of failed txs from the pool
Making the `Worker`'s `DeleteTx` to delete the tx from the DB pool using `DbManger`.

### PR DESCRIPTION
**Pull request by Psykepro**
Closes #1695

### What does this PR do?

Adding missing deletion of invalid to process txs in finalizer from pool db.

### Reviewers

Main reviewers:
- @ToniRamirezM 
- @ARR552 
- @agnusmor 

Codeowner reviewers:
- @ToniRamirezM

### CODE REVIEW

File: sequencer/finalizer.go [hunk 1]
```diff
@@ -421,6 +421,10 @@ func (f *finalizer) handleTransactionError(ctx context.Context, result *state.Pr
 		log.Errorf("ROM out of counters error, marking tx with Hash: %s as INVALID, errorCode: %s", tx.Hash.String(), errorCode.String())
 		start := time.Now()
 		f.worker.DeleteTx(tx.Hash, tx.From)
+		err := f.dbManager.UpdateTxStatus(ctx, tx.Hash, pool.TxStatusFailed)
+		if err != nil {
+			log.Errorf("failed to delete tx from pool, err: %s", err)
```
Comment (agnusmor) [inline sequencer/finalizer.go:426]: the log message must be "failed to update tx from pool, err:" (not "delete")

Comment (Psykepro) [reply sequencer/finalizer.go:426]: ops yep forgot to update the log

Comment (Psykepro) [reply sequencer/finalizer.go:426]: will make it more explicit like that:
`log.Errorf("failed to update status to failed in the pool for tx: %s, err: %s", tx.Hash.String(), err)`

**Review by ToniRamirezM — APPROVED** [review]

**Review by tclemos — APPROVED** [review]
