### PR TITLE
review Estimate Gas validations and Formulas

### LINKED ISSUE #2848: "balance intrinsic error" since 0.4.1
I've started encountering the following error when attempting to build a transaction:
`unable to apply transaction even for the highest gas limit 30000000: balance intrinsic error`

I believe this may have started at version 0.4.1, as this likely would've been raised earlier.
But because I don't know exactly what this error means, I cannot speculate as to why it is occurring (since it's a "balance error", is it failing because it's simulating through a wallet with no balance?)

ready-to-run python code at https://gist.github.com/DefiDebauchery/b4a62540af70d124ed8770b4526e447b

This is not a simple contract reversion, as I can get a revert simply by simulating the call from an address that does not have adequate Ownership to the timelock.

Expected output is a txn payload that can be submitted.
Actual output is the error reported above.

### LINKED ISSUE #2869: eth_estimateGas and eth_call error if a non-zero value is specified without a funded `from` address
#### System information

zkEVM Node version: `v0.0.X-RCXX` - unknown, whatever `https://zkevm-rpc.com` is using
OS & Version: `Windows/Linux/OSX` - OSX
Commit hash : (if `develop`)
Network: `Mainnet/Testnet` - mainnet

#### Expected behaviour

I should be able to estimate gas when calling a payable function with some value. For example, making an eth_estimateGas RPC against my smart contract at `0xaad207a0Fd7a4e3C927Ccc78ac8134baF586B852` and calling the `sendHelloWorld` function with 0.01 ETH should give me a non-error output

However it complains presumably because the default account used for eth_estimateGas is assumed to have a balance of 0:

```
$ cast estimate 0xaad207a0Fd7a4e3C927Ccc78ac8134baF586B852 'sendHelloWorld(uint32,string)' 43114 'Hello!' --rpc-url https://zkevm-rpc.com --value $(cast tw 0.01)
Error:
(code: -32000, message: insufficient funds for gas * price + value, data: None)
```

If I explicitly specify a from address with a balance, all is fine:

```
$ cast estimate 0xaad207a0Fd7a4e3C927Ccc78ac8134baF586B852 'sendHelloWorld(uint32,string)' 43114 'Hello!' --rpc-url https://zkevm-rpc.com --value $(cast tw 0.01) --from 0x5fb02f40f56d15f0442a39d11a23f73747095b20
214815
```

This is not expected behavior - all other EVM compatible chains work when estimating gas w/ value even without specifying the from address. For example, calling my same smart contract on Ethereum:

```
$ cast estimate 0x7ff2bF58C38A41AD7C9CbC14e780e8a7EDBbd48D 'sendHelloWorld(uint32,string)' 43114 'Hello!' --rpc-url https://rpc.ankr.com/eth --value $(cast tw 0.01)
171203
```

#### Actual behaviour

:(

```
$ cast estimate 0xaad207a0Fd7a4e3C927Ccc78ac8134baF586B852 'sendHelloWorld(uint32,string)' 43114 'Hello!' --rpc-url https://zkevm-rpc.com --value $(cast tw 0.01)
Error:
(code: -32000, message: insufficient funds for gas * price + value, data: None)
```

#### Steps to reproduce the behaviour

Use `cast` as done above, or manually construct the eth_estimateGas using the params specified

#### Backtrace

n/a

When submitting logs: please submit them as text and not screenshots.

### PR DESCRIPTION
**Pull request by tclemos**
Closes #2848

### What does this PR do?

review Estimate Gas validations and Formulas

### CODE REVIEW

File: state/state.go [hunk 1]
```diff
@@ -17,6 +17,10 @@ import (
 const newL2BlockEventBufferSize = 500
 
 var (
+	// DefaultSenderAddress is the address that jRPC will use
+	// to communicate with the state for eth_EstimateGas and eth_Call when
+	// the From field is not specified because it is optional
+	DefaultSenderAddress = "0x1111111111111111111111111111111111111111"
```
Comment (krlosMata) [inline state/state.go:23]: Maybe we can set here what geth does and use the `ZeroAddress`.
Then, if the `from` is unspecified, we set the from to `ZeroAddress`.

File: state/transaction.go [hunk 2]
```diff
@@ -1022,29 +1019,16 @@ func (s *State) EstimateGas(transaction *types.Transaction, senderAddress common
...
-		highEnd = s.cfg.MaxCumulativeGasUsed
-	}
-
-	var availableBalance *big.Int
-
-	if senderAddress != ZeroAddress {
+	// if sender is specified and gas price is set
+	// try to set the high end to the max value the account balance can afford
+	if isSenderSpecified && isGasPriceSet {
 		senderBalance, err := s.tree.GetBalance(ctx, senderAddress, stateRoot.Bytes())
```
Comment (krlosMata) [inline state/transaction.go:1028]: This check should be done even if `from` is not specified. It will be done with the `defaultAddress`

File: state/transaction.go [hunk 3]
```diff
@@ -1054,31 +1038,54 @@ func (s *State) EstimateGas(transaction *types.Transaction, senderAddress common
 			}
 		}
 
-		availableBalance = new(big.Int).Set(senderBalance)
-
+		availableBalance := new(big.Int).Set(senderBalance)
+		// check if the account balance is at least bigger than the tx Value
```
Comment (krlosMata) [inline state/transaction.go]: available balance to send `value` should be check for `defaultAdress` & if the `gasPrice` is not set as well

**Review by krlosMata — CHANGES_REQUESTED** [review]

**Review by ARR552 — APPROVED** [review]
LGTM
