### PR TITLE
Fix updatedeps

### LINKED ISSUE #954: Fix updatedeps GHA

### PR DESCRIPTION
**Pull request by fgimenez**
Closes #954

### What does this PR do?
* Use `PERSONAL_ACCESS_TOKEN` instead of `UPDATE_DEPS_SSH_PK` to authenticate against github API
* Update list of docker images checked by updatedeps.

### Reviewers
@arnaubennassar

### CODE REVIEW

**Review by arnaubennassar — APPROVED** [review]

**Comment by fgimenez** [comment]
All green and execution of updatedeps successful from this branch https://github.com/0xPolygonHermez/zkevm-node/runs/7558377134?check_suite_focus=true, merging

File: scripts/cmd/dependencies.go [hunk 1]
```diff
@@ -8,16 +8,16 @@ import (
 func updateDeps(ctx *cli.Context) error {
 	cfg := &dependencies.Config{
 		Images: &dependencies.ImagesConfig{
-			Names:          []string{"hermeznetwork/geth-zkevm-contracts", "hermeznetwork/zkevm-mock-prover"},
+			Names:          []string{"hermeznetwork/geth-zkevm-contracts", "hermeznetwork/zkprover-local"},
```
Comment (ARR552) [inline scripts/cmd/dependencies.go:11]: Maybe we need to use the new 0xPolygonHermez instead fo hermeznetwork

**Review by ARR552 — APPROVED** [review]

File: scripts/cmd/dependencies.go (hunk 1 above)
Comment (fgimenez) [reply scripts/cmd/dependencies.go:11]: Well, these are docker image names as found in docker-compose.yml. Not sure if there's a new `0xPolygonHermez` in Docker Hub, in any case, the image names here should match what we have in docker-compose.yml (as they do now), and both should be updated at the same time.
