### PR TITLE
event log

### LINKED ISSUE #1605: Improve debug table behaviour
- Add a label to understand what component is logging the error (sequencer, sync, ...)
- Encode byte arrays in hexa instead of base 64 (default conversion done by Go)
- capture the executor top level error, not only the request
- capture requests also when something unexpected happens even if there is not a top level error from the executor (for instance an error on the RLP or tx hash decoding)

### LINKED ISSUE #1832: Move debug and event tables out to the state schema

### PR DESCRIPTION
**Pull request by ToniRamirezM**
Closes #1605
Closes #1832 

### What does this PR do?

Creates an event log component.

### Reviewers

Main reviewers:

- @ARR552 
- @agnusmor 
- @tclemos 
- @xavier-romero

### CODE REVIEW

File: cmd/run.go [hunk 1]
```diff
@@ -72,6 +75,24 @@ func start(cliCtx *cli.Context) error {
 	}
 	checkStateMigrations(c.StateDB)
 
+	// Prepare event log
+	var eventLog *event.EventLog
+	var eventStorage event.Storage
+
+	if c.EventLog.DB.Name != "disabled" {
```
Comment (agnusmor) [inline cmd/run.go:82]: What happens if the EventLog.DB entry doesn't exists in the config file? if it doesn't exists we need to manage it in the same way if it have the "disabled" value. For non-trusted nodes (that will not use the event table) it will be more easy to avoid the creation of the [EventLog] [EventLog.DB] sections in the config file, it will be more transparent.

File: event/pgeventstorage/pgeventstorage.go [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+func (p *PostgresEventStorage) Close() error {
+	p.db.Close()
+	return nil
+}
+
+// LogEvent logs an event to the database
+func (p *PostgresEventStorage) LogEvent(ctx context.Context, ev *event.Event) error {
+	const insertEventSQL = "INSERT INTO event (received_at, ip_address, source, component, level, event_id, description, data, json) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)"
+
+	switch ev.Level {
```
Comment (agnusmor) [inline event/pgeventstorage/pgeventstorage.go:40]: We have this same code in the LogEvent function to the NilEventStorage package, there is no way to have a common function for this or reuse the NilEventStorage.LogEvent function? this is to avoid duplicate code as maybe in the future we can miss update on of the 2 codes when doing a change related to this

File: cmd/run.go (hunk 1 above)
Comment (ToniRamirezM) [reply cmd/run.go:82]: This disabled literal will be read from the default.go so it does not need to be in the config toml files

File: db/migrations/state/0005.sql [hunk 3]
```diff
@@ -0,0 +1,20 @@
+-- +migrate Up
+DROP table state.event;
+DROP table state.debug;
+
+-- +migrate Down
+CREATE TABLE state.event
```
Comment (ARR552) [inline db/migrations/state/0005.sql:6]: I'd prefer to use `IF NOT EXIST` to avoid problems. I know this situation shouldn't happen in theory

File: event/nileventstorage/nileventstorage.go [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+		log.Errorf("Event: %+v", ev)
+	case event.Level_Warning:
+		log.Warnf("Event: %+v", ev)
+	case event.Level_Notice:
+		log.Infof("Event: %+v", ev)
+	case event.Level_Info:
+		log.Infof("Event: %+v", ev)
+	case event.Level_Debug:
+		log.Debugf("Event: %+v", ev)
+	}
```
Comment (ARR552) [inline event/nileventstorage/nileventstorage.go:45]:
```suggestion
	switch ev.Level {
	case event.Level_Emergency, event.Level_Alert, event.Level_Critical, event.Level_Error:
		log.Errorf("Event: %+v", ev)
	case event.Level_Warning:
		log.Warnf("Event: %+v", ev)
	case event.Level_Notice, event.Level_Info::
		log.Infof("Event: %+v", ev)
	case event.Level_Debug:
		log.Debugf("Event: %+v", ev)
	}
```

**Review by agnusmor — APPROVED** [review]

**Review by ARR552 — APPROVED** [review]

**Review by agnusmor — APPROVED** [review]
