### PR TITLE
synchronizer feijoa Part 2

### LINKED ISSUE #3389: Synchronizer must deal with discrepancies in StateRoot when syncing from L2 a closed batch
# Rationale

Currently if `synchronizer` synchronize a batch from TrustedNode and doesn't match StateRoot but is closed it keep syncing from L2, maybe make sense to stop trying and update from L1 to get the Virtualized Batch

It produce next log: 
```
syncTrustedState: batch[57074/57076] mode nothing: error processing trusted batch. Error: when closing the batch, the batch is already close, but  the data on state doesnt match the expected
```

### PR DESCRIPTION
**Pull request by joanestebanr**
Closes #3389
### What does this PR do?

Process InnerBlob and split in batches. 
- It doesn't store batches yet because it need to calculate the batchNumber
- The prover required is `hermeznetwork/zkevm-prover:v7.0.0-RC4` (the docker-compose.yml use v6.0.0 to be compatible with aggregator)
### Reviewers

Main reviewers:

- @ARR552 
- @tclemos 
- @agnusmor 

Codeowner reviewers:

- @-Alice
- @-Bob

### CODE REVIEW

File: db/migrations/state/0023.sql [hunk 1]
```diff
@@ -1,18 +1,57 @@
...
-CREATE TABLE state.blob_sequence
+CREATE TABLE IF NOT EXISTS state.blob_sequence
 (
     index                BIGINT PRIMARY KEY,
     coinbase             VARCHAR,
     final_acc_input_hash VARCHAR,
     first_blob_sequenced  BIGINT,
     last_blob_sequenced   BIGINT,
     created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
+    recevied_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
```
Comment (tclemos) [inline db/migrations/state/0023.sql]: Typo

File: db/migrations/state/0023.sql [hunk 2]
```diff
@@ -1,18 +1,57 @@
...
     block_num          BIGINT NOT NULL REFERENCES state.block (block_num) ON DELETE CASCADE 
 );
 
+comment on column state.blob_sequence.index is 'Is a id of this sequence, this value is internal and incremental';
+comment on column state.blob_sequence.block_num is 'L1 Block where appear this sequence';
+comment on column state.blob_sequence.first_blob_sequenced is 'first (included) blob_inner_num of this sequence (state.blob_inner.blob_inner_num)';
+comment on column state.blob_sequence.first_blob_sequenced is 'last (included) blob_inner_num of this sequence (state.blob_inner.blob_inner_num)';
+comment on column state.blob_sequence.recevied_at is 'time when it was received in node';
```
Comment (tclemos) [inline db/migrations/state/0023.sql]: Typo

File: db/migrations/state/0023.sql [hunk 3]
```diff
@@ -1,18 +1,57 @@
...
+    blob_type_y      VARCHAR,
+    blob_type_commitment VARCHAR,
+    blob_type_proof VARCHAR
+);
+
+comment on column state.blob_inner_in.updated_at is 'the creation time is blob_sequence.created_at, this is the last time when was updated (tipically Now() )';
+comment on column state.blob_inner_in.blob_type is 'call_data, blob or forced';
+comment on column state.blob_inner_in.blob_data_hash is 'is the hash of the blobData';
 
+CREATE TABLE IF NOT EXISTS state.incomming_batch
```
Comment (tclemos) [inline db/migrations/state/0023.sql]: Typo

File: db/migrations/state/0023.sql [hunk 4]
```diff
@@ -1,18 +1,57 @@
...
+(
+    batch_num                BIGINT PRIMARY KEY,
+    blob_inner_num          BIGINT NOT NULL REFERENCES state.blob_inner_in (blob_inner_num) ON DELETE CASCADE,
+    data           BYTEA,
+    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),   
+    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
+); 
 
 -- +migrate Down
+DROP TABLE IF EXISTS state.incomming_batch;
```
Comment (tclemos) [inline db/migrations/state/0023.sql]: Typo

**Review by tclemos — APPROVED** [review]
I think it worth fixing the typos for now

File: db/migrations/state/0023.sql [hunk 5]
```diff
@@ -1,18 +1,57 @@
...
     coinbase             VARCHAR,
     final_acc_input_hash VARCHAR,
     first_blob_sequenced  BIGINT,
     last_blob_sequenced   BIGINT,
     created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
+    recevied_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
     block_num          BIGINT NOT NULL REFERENCES state.block (block_num) ON DELETE CASCADE 
 );
 
+comment on column state.blob_sequence.index is 'Is a id of this sequence, this value is internal and incremental';
```
Comment (ARR552) [inline db/migrations/state/0023.sql]:
```suggestion
comment on column state.blob_sequence.index is 'It is the id of the sequence, this value is internal and incremental';
```

File: db/migrations/state/0023.sql [hunk 6]
```diff
@@ -1,18 +1,57 @@
...
+comment on column state.blob_sequence.block_num is 'L1 Block where appear this sequence';
+comment on column state.blob_sequence.first_blob_sequenced is 'first (included) blob_inner_num of this sequence (state.blob_inner.blob_inner_num)';
+comment on column state.blob_sequence.first_blob_sequenced is 'last (included) blob_inner_num of this sequence (state.blob_inner.blob_inner_num)';
+comment on column state.blob_sequence.recevied_at is 'time when it was received in node';
+comment on column state.blob_sequence.created_at is 'time when was created on L1 (L1block tstamp)';
+
+CREATE TABLE IF NOT EXISTS state.blob_inner_in
```
Comment (ARR552) [inline db/migrations/state/0023.sql:22]: What about just name it as state.blob_inner?

File: etherman/feijoa_event_sequence_blobs.go [hunk 7]
```diff
@@ -151,12 +149,25 @@ func parseBlobCallDataTypeParams(data []byte) (*BlobCommonParams, []byte, error)
...
+	uint64Ty, _ := abi.NewType("uint64", "", nil)
+	uint32Ty, _ := abi.NewType("uint32", "", nil)
+	bytesTy, _ := abi.NewType("bytes", "", nil)
+	arguments := abi.Arguments{
+		{Type: uint64Ty},
+		{Type: uint64Ty},
+		{Type: uint32Ty},
+		{Type: bytesTy},
+	}
+	unpacked, err := arguments.Unpack(data)
```
Comment (ARR552) [inline etherman/feijoa_event_sequence_blobs.go:163]: I think this could be done using anonymous structs and using marshall/unmarshall
https://www.willem.dev/articles/anonymous-structs/

File: synchronizer/default_l1processors.go [hunk 8]
```diff
@@ -26,6 +26,6 @@ func defaultsL1EventProcessors(sync *ClientSynchronizer, l2Blockchecker *actions
 	p.Register(actions.NewCheckL2BlockDecorator(elderberry.NewProcessorL1SequenceBatchesElderberry(sequenceBatchesProcessor, sync.state), l2Blockchecker))
 	// intialSequence is process in ETROG by the same class, this is just a wrapper to pass directly to ETROG
 	p.Register(elderberry.NewProcessorL1InitialSequenceBatchesElderberry(sequenceBatchesProcessor))
-	p.Register(feijoa.NewProcessorSequenceBlobs(sync.state))
+	p.Register(feijoa.NewProcessorSequenceBlobs(sync.state, sync.state, nil))
```
Comment (ARR552) [inline synchronizer/default_l1processors.go:29]: why sync.state is needed twice? Could we remove the nil param?? If it is not used.Why is the purpose of keeping it?

File: db/migrations/state/0023.sql (hunk 6 above)
Comment (joanestebanr) [reply db/migrations/state/0023.sql:22]: This name was used by Aggregator branch, until we don't merge both changes and understand if it's the same I think that is better to keep separated

File: synchronizer/default_l1processors.go (hunk 8 above)
Comment (joanestebanr) [reply synchronizer/default_l1processors.go:29]: Because one is the objected related to Database and the other one is the object related to Executor. That is relevant in tests and also, from the point of view of this class is not assuming that both parts are implemented by the same object

File: etherman/feijoa_event_sequence_blobs.go (hunk 7 above)
Comment (joanestebanr) [reply etherman/feijoa_event_sequence_blobs.go:163]: What do you mean? instead of using **abi.Arguments**?
