### PR TITLE
#3514  Fix l1 info root after reorg

### LINKED ISSUE #3514: Issue with L1InfoRoots after a reorg

### PR DESCRIPTION
**Pull request by ARR552**
Closes #3514 

### What does this PR do?

This PR forced the synchronizer to reset the L1InfoRoot memory variables

### Reviewers

- @joanestebanr 
- @tclemos 
- @agnusmor

### CODE REVIEW

**Review by joanestebanr — APPROVED** [review]

**Review by agnusmor — APPROVED** [review]

**Review by agnusmor — APPROVED** [review]

File: state/reset.go [hunk 1]
```diff
@@ -13,12 +14,20 @@ func (s *State) Reset(ctx context.Context, blockNumber uint64, dbTx pgx.Tx) erro
...
+	err = s.ResetL1InfoTree(ctx, dbTx)
+	if err != nil {
+		log.Error("error resetting the l1InfoTree. Error: ", err)
+		return err
+	}
+	// Discard L1InfoTree cache
+	// We can't rebuild cache, because we are inside a transaction, so we dont known
+	// is going to be a commit or a rollback. So is going to be rebuild on the next
+	// request that needs it.
+	s.l1InfoTree = nil
```
Comment (tclemos) [inline state/reset.go:25]: What's the point of setting the L1InfoTree as nil right after reseting it?

File: synchronizer/synchronizer.go [hunk 2]
```diff
@@ -752,7 +754,8 @@ func (s *ClientSynchronizer) checkReorg(latestBlock *state.Block) (*state.Block,
 				log.Errorf("error creating db transaction to get prevoius blocks")
 				return nil, err
 			}
-			latestBlock, err = s.state.GetPreviousBlock(s.ctx, depth, dbTx)
+			lb, err := s.state.GetPreviousBlock(s.ctx, depth, dbTx)
+			reorgedBlock = *lb
```
Comment (tclemos) [inline synchronizer/synchronizer.go]: I think lb can be nil here if err is not nil, right? The *lb will panic if lb is nil

**Review by tclemos — CHANGES_REQUESTED** [review]

File: synchronizer/synchronizer.go (hunk 2 above)
Comment (ARR552) [reply synchronizer/synchronizer.go]: great catch!

**Review by tclemos — APPROVED** [review]
