### PR TITLE
Review some logging levels in JSON-RPC component

### LINKED ISSUE #1269: Review some log levels for jRPC
- Failed txs (estimate gas, eth call) shouldn't be logged as error, it's completely OK to receive txs that are reverted or fail
- Upgrade the log level for the requests `debug ==> info`

### PR DESCRIPTION
**Pull request by KonradIT**
Closes #1269

### What does this PR do?

Changed some logging levels to clean up the `error` timeline, and moved some `debug` logs to `info`.

### Reviewers

Main reviewers:

- @arnaubennassar 
- @tclemos 
- @ToniRamirezM 

Codeowner reviewers:

### CODE REVIEW

**Comment by KonradIT** [comment]
### Todo:

- [ ] Find `panic` errors: Haven't found any in RPC side, the ones that exist are for tests, and should remain there
- [ ] More descriptive errors and better handling of pointer vars

File: ethtxmanager/ethtxmanager.go [hunk 1]
```diff
@@ -142,7 +142,7 @@ func (c *Client) VerifyBatch(ctx context.Context, batchNum uint64, resGetProof *
 				log.Infof("tx %s reached timeout, retrying with gas price = %d", tx.Hash(), gasPrice)
 				continue
 			}
-			log.Errorf("tx %s failed, err: %w", tx.Hash(), err)
+			log.Infof("tx %s failed, err: %w", tx.Hash(), err)
```
Comment (arnaubennassar) [inline ethtxmanager/ethtxmanager.go:145]: this looks like an actual error

**Review by arnaubennassar — CHANGES_REQUESTED** [review]

**Review by arnaubennassar — APPROVED** [review]
