### PR TITLE
sort logs by tx hash and then by log index

### LINKED ISSUE #3446: Incorrect `logIndex` in JSON RPC responses
#### System information

zkEVM Node version: `v0.5.13`
Network: `Mainnet`

#### Expected behaviour

JSON RPC calls to `eth_getLogs`, `eth_getTransactionReceipt` and others returning execution logs contain `logIndex` field.

According to https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getfilterchanges:
> logIndex: QUANTITY - integer of the log index position in the block. null when its pending log.

Therefore returned log indices should be unique per block.

#### Actual behaviour

Returned `logIndex` values are calculated per-transaction, and therefore are not unique in block. This breaks compatibility with external tooling built on top of zkEVM JSON RPC.

```shell
$ curl -s 'https://zkevm-rpc.com' --header 'Content-Type: application/json' --data '{"jsonrpc":"2.0","id":2,"method":"eth_getLogs","params":[{"blockHash":"0x0120265d4072d3773482b9de80a63e9349391f10fe05ba317751db7e0295676a"}]}' | jq .
{
  "jsonrpc": "2.0",
  "id": 2,
  "result": [
    {
      "address": "0x1e4a5963abfd975d8c9021ce480b42188849d41d",
      "topics": [
        "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
        "0x0000000000000000000000001d09305a90fe173f596f8361ba86c9adb2a58de4",
        "0x000000000000000000000000ad41c77d99e282267c1492cdefe528d7d5044253"
      ],
      "data": "0x00000000000000000000000000000000000000000000000000000000caa7e200",
      "blockNumber": "0x996211",
      "transactionHash": "0x12346c7a3e7aafff2aff5ab3e940b9d039270e155c57a08886789981414409e1",
      "transactionIndex": "0x0",
      "blockHash": "0x0120265d4072d3773482b9de80a63e9349391f10fe05ba317751db7e0295676a",
      "logIndex": "0x0",
      "removed": false
    },
    {
      "address": "0xb58f5110855fbef7a715d325d60543e7d4c18143",
      "topics": [
        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
        "0x0000000000000000000000000000000000000000000000000000000000000000",
        "0x0000000000000000000000001885597ca499c1b460ef30248bdc5c28f5c75c93",
        "0x0000000000000000000000000000000000000000000000000000000000b783e5"
      ],
      "data": "0x",
      "blockNumber": "0x996211",
      "transactionHash": "0x42b24fb2755c8f3e46dbdeb0a1ab242979064f2310b06a4c4b5c859d96574454",
      "transactionIndex": "0x1",
      "blockHash": "0x0120265d4072d3773482b9de80a63e9349391f10fe05ba317751db7e0295676a",
      "logIndex": "0x0",
      "removed": false
    },
    {
      "address": "0x4f9a0e7fd2bf6067db6994cf12e4495df938e6e9",
      "topics": [
        "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c",
        "0x000000000000000000000000f081470f5c6fbccf48cc4e5b82dd926409dcdd67"
      ],
      "data": "0x00000000000000000000000000000000000000000000000000071afd498d0000",
      "blockNumber": "0x996211",
      "transactionHash": "0xa31684f521588d13be5393074bc0f9939a10a465091a8bd1e270c29d8d1a170a",
      "transactionIndex": "0x2",
      "blockHash": "0x0120265d4072d3773482b9de80a63e9349391f10fe05ba317751db7e0295676a",
      "logIndex": "0x0",
      "removed": false
    },
    {
      "address": "0x4f9a0e7fd2bf6067db6994cf12e4495df938e6e9",
      "topics": [
        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
        "0x000000000000000000000000f081470f5c6fbccf48cc4e5b82dd926409dcdd67",
        "0x00000000000000000000000003a9a6a8f62af9376a83c391fd90eeeea67fad6c"
      ],
      "data": "0x00000000000000000000000000000000000000000000000000071afd498d0000",
      "blockNumber": "0x996211",
      "transactionHash": "0xa31684f521588d13be5393074bc0f9939a10a465091a8bd1e270c29d8d1a170a",
      "transactionIndex": "0x2",
      "blockHash": "0x0120265d4072d3773482b9de80a63e9349391f10fe05ba317751db7e0295676a",
      "logIndex": "0x1",
      "removed": false
    },
    ...
  ]
}
```

#### Steps to reproduce the behaviour

```shell
$ curl -s 'https://zkevm-rpc.com' --header 'Content-Type: application/json' --data '{"jsonrpc":"2.0","id":2,"method":"eth_getLogs","params":[{"blockHash":"0x0120265d4072d3773482b9de80a63e9349391f10fe05ba317751db7e0295676a"}]}' | jq .
```

When submitting logs: please submit them as text and not screenshots.

### PR DESCRIPTION
**Pull request by tclemos**
Closes #3446.

### What does this PR do?

minimize the logIndex bug introduced on Etrog sorting logs by tx hash and then by log index

### CODE REVIEW

File: state/pgstatestorage/pgstatestorage.go [hunk 1]
```diff
@@ -128,7 +128,7 @@ func (p *PostgresStorage) GetLogsByBlockNumber(ctx context.Context, blockNumber
        INNER JOIN state.l2block b ON b.block_num = t.l2_block_num
        INNER JOIN state.receipt r ON r.tx_hash = t.hash
        WHERE b.block_num = $1
-       ORDER BY l.log_index ASC`
+       ORDER BY r.tx_index, l.log_index ASC`
```
Comment (agnusmor) [inline state/pgstatestorage/pgstatestorage.go]: is it no better to indicate explicitly that we want to sort in  ASC order the tx_index field?

File: state/pgstatestorage/pgstatestorage.go [hunk 2]
```diff
@@ -159,7 +159,7 @@ func (p *PostgresStorage) GetLogs(ctx context.Context, fromBlock uint64, toBlock
 	const queryFilterByBlockHash = `AND b.block_hash = $7 `
 	const queryFilterByBlockNumbers = `AND b.block_num BETWEEN $7 AND $8 `
 
-	const queryOrder = `ORDER BY b.block_num ASC, l.log_index ASC`
+	const queryOrder = `ORDER BY b.block_num ASC, r.tx_index, l.log_index ASC`
```
Comment (agnusmor) [inline state/pgstatestorage/pgstatestorage.go]: is it no better to indicate explicitly that we want to sort in  ASC order the tx_index field? we indicate this for block_num and log_index but not for tx_index field

**Review by agnusmor — APPROVED** [review]
