### PR TITLE
Potential fix oversized data

### LINKED ISSUE #1074: Oversized data
Error detected during a Smartcontract deployment.
```
2022-08-22T06:40:59Z    FATAL   ethtxmanager/ethtxmanager.go:45 failed to sequence batches, maximum attempts exceeded, gasLimit: 0, err: oversized data%!(EXTRA string=
/src/log/log.go:106 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:158 github.com/0xPolygonHermez/zkevm-node/log.Fatalf()
/src/ethtxmanager/ethtxmanager.go:45 github.com/0xPolygonHermez/zkevm-node/ethtxmanager.(*Client).SequenceBatches()
/src/sequencer/sequencesender.go:42 github.com/0xPolygonHermez/zkevm-node/sequencer.(*Sequencer).tryToSendSequence()
/src/sequencer/sequencer.go:137 github.com/0xPolygonHermez/zkevm-node/sequencer.(*Sequencer).Start.func2()
)
```

### PR DESCRIPTION
**Pull request by KonradIT**
<h1>do not merge - wip</h1>

Closes #1074.

### What does this PR do?

Attempts to fix the oversized data issue.

### Reviewers

Main reviewers:

- @ARR552 
- @arnaubennassar 

Codeowner reviewers:

### CODE REVIEW

File: sequencer/batchbuilder.go [hunk 1]
```diff
@@ -59,6 +61,49 @@ func (s *Sequencer) tryToProcessTx(ctx context.Context, ticker *time.Ticker) {
...
+			err := s.pool.UpdateTxState(ctx, s.sequenceInProgress.Txs[0].Hash(), pool.TxStateInvalid)
+			if err != nil {
+				log.Errorf("failed to update tx status on the pool, err: %w", err)
+				return
+			}
+			// rm tx from sequenceInProgress
+			s.sequenceInProgress.Txs = []ethtypes.Transaction{}
+		} else {
+
+			// rm tx from sequenceInProgress
```
Comment (arnaubennassar) [inline sequencer/batchbuilder.go:82]: Add log with level `INFO` explaining why the batch is being closed

**Review by arnaubennassar — CHANGES_REQUESTED** [review]
Let's not merge this until it's more clear the origin of the bug this is trying to fix

**Review by arnaubennassar — APPROVED** [review]
