### PR TITLE
fix L1InfoRoot when an error happens during the process of the L1 information

### LINKED ISSUE #3573: Fix reset l1InfoTree if an error happens processing rollup information
Log:
```
2024-04-19T12:31:55.085Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492344, BlockNumber: 5711797	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:31:55.086Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492345, BlockNumber: 5711797 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:31:57.720Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2417	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:31:57.720Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492345, BlockNumber: 5711797	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:31:57.721Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492346, BlockNumber: 5711797 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:00.773Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2418	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:00.773Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492346, BlockNumber: 5711797	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:00.774Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492347, BlockNumber: 5711797 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:03.834Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2419	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:03.834Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492347, BlockNumber: 5711797	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:03.835Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492348, BlockNumber: 5711797 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:06.672Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2420	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:06.672Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492348, BlockNumber: 5711797	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:07.587Z	INFO	actions/check_l2block.go:125	checkL2block: L2BlockNumber: 13381559  checked L2Block in the database  and the trusted batch are the same 0x23fc3a336f7f112934a942d4b0b848e17e96583b00d38e05fe17e8c842cc9919	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:07.592Z	INFO	synchronizer/synchronizer.go:935	executor vs local: flushid=2420/2420, proverID=dedcaa44-fc0f-4f85-b7fb-15e00e8b24ed/dedcaa44-fc0f-4f85-b7fb-15e00e8b24ed	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:07.592Z	INFO	synchronizer/synchronizer.go:960	Pending Flushid fullfiled: 2420, executor have write 2420	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:07.595Z	INFO	etrog/processor_l1_info_tree_update.go:52	L1InfoTree(etrog) stored. BlockNumber: 5711801,GER:0xa0505e46901f26ea67148ba83c511da86a8c7300654ab798a102f4130f378857 L1InfoTreeIndex: 94439 L1InfoRoot:0x52e2bbe8fd849f2a55971fbc7bd27ad457f11e65b13691ae1688e36e5d2b7797	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:07.596Z	INFO	synchronizer/synchronizer.go:582	Syncing block 5711807 of 5731520	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:07.596Z	INFO	synchronizer/synchronizer.go:583	Getting rollup info from block 5711807 to block 5711907	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:08.247Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0xf1bd543ba8ed4e9b297beb767af12f5260ad31416c2597fa9d0b4475abbe41a1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:08.251Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492349 492350 492351 492352 492353 492354 492355 492356 492357 492358 492359 492360 492361 492362 492363 492364 492365 492366 492367 492368]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:09.386Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x76938bbe53960b82667c1ca966df5577bfec361d3afad71fd4cb231c1ff153a9, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:09.388Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492369 492370 492371 492372 492373 492374 492375 492376 492377 492378 492379 492380 492381 492382 492383 492384 492385 492386 492387 492388]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:10.594Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x09b69c728c38bb8abef60243fac35b30dab4b08af4de37c9c741dc63566ddcf1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:10.596Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492389 492390 492391 492392 492393 492394 492395 492396 492397 492398 492399 492400 492401 492402 492403 492404 492405 492406 492407 492408]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.586Z	INFO	synchronizer/synchronizer.go:812	[checkReorg function] BlockNumber: 5711801 BlockHash got from L1 provider: 0x576b67c522eda4a4fff6ce14234b5eb6c29ffdb9ed8f74a8392bd8e8e15fbc6e	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.586Z	INFO	synchronizer/synchronizer.go:813	[checkReorg function] latestBlockNumber: 5711801 latestBlockHash already synced: 0x576b67c522eda4a4fff6ce14234b5eb6c29ffdb9ed8f74a8392bd8e8e15fbc6e	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.587Z	INFO	etrog/processor_l1_info_tree_update.go:52	L1InfoTree(etrog) stored. BlockNumber: 5711811,GER:0x9fe9654b0fae76520594321baa5f5ed30b61aca5b0743d924fd35ee13c25240f L1InfoTreeIndex: 94440 L1InfoRoot:0x772c2b061f4cd22a5a053d091187b759f27fe8ee83527243b98f09463199abb4	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.587Z	INFO	etrog/processor_l1_info_tree_update.go:52	L1InfoTree(etrog) stored. BlockNumber: 5711811,GER:0xe4e5260488e15aa1d6af68928e17146490372679662f3c14b1365dbe1e870b93 L1InfoTreeIndex: 94441 L1InfoRoot:0x65683adb12dfc8db618b41d13c6cc61c54553c4f2e3a4a9c6dcab95c73e2538d	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.588Z	INFO	etrog/processor_l1_info_tree_update.go:52	L1InfoTree(etrog) stored. BlockNumber: 5711813,GER:0x11613c36e51f2664ce10af6abec1bd4ce53c822c6ff48d40b686522f34dd9c86 L1InfoTreeIndex: 94442 L1InfoRoot:0x70663b2da4184f328500bd1da14093d68a385cdc5ca1734bb4bc8f7a5bec7523	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.590Z	INFO	etrog/processor_l1_info_tree_update.go:52	L1InfoTree(etrog) stored. BlockNumber: 5711819,GER:0x0ff0d55dd975f619976b72c580f574f500c74ab5efa7e7159adb0593db42a55e L1InfoTreeIndex: 94443 L1InfoRoot:0xe550ac242f730fdec346fedfaa3f6d70e656a2ec01f8850cc573c2ef22de6d1d	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.591Z	INFO	etrog/processor_l1_info_tree_update.go:52	L1InfoTree(etrog) stored. BlockNumber: 5711824,GER:0x8ee17708cbe3827c9d82868f239aa75d0f2781ecaad95e2f8a32cba93415c693 L1InfoTreeIndex: 94444 L1InfoRoot:0xac4e638e45ef9be9f5b84052a0a08df230f892190b742bf878445404d177670b	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.592Z	INFO	etrog/processor_l1_info_tree_update.go:52	L1InfoTree(etrog) stored. BlockNumber: 5711827,GER:0x9708a2261fb346b73dafb4ccc9d0db9820d6d80f89bd967ec5565732bbf1ad59 L1InfoTreeIndex: 94445 L1InfoRoot:0x109f037052642931751c5ce45588edcbec2361ee8ef37deacaf8e065c1535c4c	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.593Z	INFO	etrog/processor_l1_info_tree_update.go:52	L1InfoTree(etrog) stored. BlockNumber: 5711829,GER:0x7d0b31da46b541b70fb00c25c425dc0fba84dde51681490fa28b9bfddfcd4996 L1InfoTreeIndex: 94446 L1InfoRoot:0xbe5c5edf2085c723879864ca013f417f000b9fa732665bd465f9ad9590d64626	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:11.594Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492349, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:14.100Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2421	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:14.100Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492349, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:14.101Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492350, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:16.772Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2422	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:16.773Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492350, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:16.773Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492351, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:19.628Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2423	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:19.628Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492351, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:19.654Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492352, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:22.723Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2424	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:22.723Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492352, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:22.724Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492353, BlockNumber: 5711829 GER:0xedf6d278a4dffbc4852834b351750919fe87214a509ba4a6f9e6e1dce471962d	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:25.526Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2425	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:25.526Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492353, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:25.526Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492354, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:28.073Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2426	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:28.073Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492354, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:28.074Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492355, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:30.968Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2427	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:30.968Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492355, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:30.969Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492356, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:33.646Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2428	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:33.646Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492356, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:33.646Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492357, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:36.309Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2429	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:36.309Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492357, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:36.310Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492358, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:39.124Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2430	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:39.124Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492358, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:39.124Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492359, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:41.860Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2431	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:41.860Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492359, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:41.861Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492360, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:44.942Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2432	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:44.942Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492360, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:44.943Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492361, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:47.793Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2433	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:47.793Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492361, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:47.794Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492362, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:50.645Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2434	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:50.645Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492362, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:50.646Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492363, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:53.407Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2435	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:53.408Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492363, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:53.408Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492364, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:56.172Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2436	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:56.172Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492364, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:56.173Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492365, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:59.255Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2437	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:59.255Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492365, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:32:59.256Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492366, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:02.497Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2438	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:02.497Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492366, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:02.498Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492367, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:05.573Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2439	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:05.573Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492367, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:05.574Z	INFO	etrog/processor_l1_sequence_batches.go:227	processSequenceBatches: (not found batch) ProcessAndStoreClosedBatch . BatchNumber: 492368, BlockNumber: 5711829 GER:0x0000000000000000000000000000000000000000000000000000000000000000	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:08.698Z	INFO	synchronizer/synchronizer.go:878	pending flushID: 2440	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:08.698Z	INFO	etrog/processor_l1_sequence_batches.go:323	processSequenceBatches: Storing virtualBatch. BatchNumber: 492368, BlockNumber: 5711829	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:08.952Z	ERROR	actions/check_l2block.go:97	checkL2block: Error getting L2Block 13381590 from the Trusted RPC. err:429 Too Many Requests: server is too busy
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions.(*CheckL2BlockHash).GetL2Blocks
	/src/synchronizer/actions/check_l2block.go:97
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions.(*CheckL2BlockHash).iterationCheckL2Block
	/src/synchronizer/actions/check_l2block.go:106
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions.(*CheckL2BlockHash).CheckL2Block
	/src/synchronizer/actions/check_l2block.go:63
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions.(*CheckL2BlockProcessorDecorator).Process
	/src/synchronizer/actions/check_l2block_processor_decorator.go:33
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:08.952Z	ERROR	actions/check_l2block.go:112	checkL2block: L2BlockNumber: 13381590  Error getting  from the database and trusted. err: 429 Too Many Requests: server is too busy
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions.(*CheckL2BlockHash).iterationCheckL2Block
	/src/synchronizer/actions/check_l2block.go:112
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions.(*CheckL2BlockHash).CheckL2Block
	/src/synchronizer/actions/check_l2block.go:63
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions.(*CheckL2BlockProcessorDecorator).Process
	/src/synchronizer/actions/check_l2block_processor_decorator.go:33
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:08.952Z	ERROR	synchronizer/synchronizer.go:706	error: 429 Too Many Requests: server is too busy

/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
/src/synchronizer/synchronizer.go:706 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:706
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:08.953Z	WARN	synchronizer/synchronizer.go:458	error syncing blocks: 429 Too Many Requests: server is too busy
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:458
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:08.954Z	INFO	synchronizer/synchronizer.go:474	L1 state fully synchronized	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:08.985Z	INFO	synchronizer/synchronizer.go:404	latestSequencedBatchNumber: 501068, latestSyncedBatch: 492348, lastVerifiedBatchNumber: 501028	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:08.985Z	INFO	synchronizer/synchronizer.go:453	Syncing L1 blocks sequentially lastEthBlockSynced=5711827	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:09.034Z	INFO	synchronizer/synchronizer.go:812	[checkReorg function] BlockNumber: 5711827 BlockHash got from L1 provider: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:09.034Z	INFO	synchronizer/synchronizer.go:813	[checkReorg function] latestBlockNumber: 5711827 latestBlockHash already synced: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:09.034Z	INFO	synchronizer/synchronizer.go:582	Syncing block 5711828 of 5731646	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:09.034Z	INFO	synchronizer/synchronizer.go:583	Getting rollup info from block 5711828 to block 5711928	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:09.202Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0xf1bd543ba8ed4e9b297beb767af12f5260ad31416c2597fa9d0b4475abbe41a1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:09.204Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492349 492350 492351 492352 492353 492354 492355 492356 492357 492358 492359 492360 492361 492362 492363 492364 492365 492366 492367 492368]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:10.280Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x76938bbe53960b82667c1ca966df5577bfec361d3afad71fd4cb231c1ff153a9, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:10.281Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492369 492370 492371 492372 492373 492374 492375 492376 492377 492378 492379 492380 492381 492382 492383 492384 492385 492386 492387 492388]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:10.968Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x09b69c728c38bb8abef60243fac35b30dab4b08af4de37c9c741dc63566ddcf1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:10.970Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492389 492390 492391 492392 492393 492394 492395 492396 492397 492398 492399 492400 492401 492402 492403 492404 492405 492406 492407 492408]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:12.419Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x69e2dde20b28b558e1cfc02256e994e0d9a7e636810d27d6f63484915725adde, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:12.421Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492409 492410 492411 492412 492413 492414 492415 492416 492417 492418 492419 492420 492421 492422 492423 492424 492425 492426 492427 492428]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.348Z	INFO	synchronizer/synchronizer.go:812	[checkReorg function] BlockNumber: 5711827 BlockHash got from L1 provider: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.348Z	INFO	synchronizer/synchronizer.go:813	[checkReorg function] latestBlockNumber: 5711827 latestBlockHash already synced: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.349Z	ERROR	state/l1infotree.go:73	error add new leaf to the L1InfoTree. Error: mismatched leaf count: 94446, expected: 94447
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
/src/state/l1infotree.go:73 github.com/0xPolygonHermez/zkevm-node/state.(*State).AddL1InfoTreeLeaf()
/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:47 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process()
/src/synchronizer/actions/processor_manager/processor_manager.go:66 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process()
/src/synchronizer/synchronizer.go:704 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/state.(*State).AddL1InfoTreeLeaf
	/src/state/l1infotree.go:73
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process
	/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:47
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:13.365Z	ERROR	etrog/processor_l1_info_tree_update.go:49	error storing the l1InfoTree(etrog). BlockNumber: 5711829, error: mismatched leaf count: 94446, expected: 94447%!(EXTRA string=
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:251 github.com/0xPolygonHermez/zkevm-node/log.Errorf()
/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:49 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process()
/src/synchronizer/actions/processor_manager/processor_manager.go:66 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process()
/src/synchronizer/synchronizer.go:704 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
)	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process
	/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:49
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:13.365Z	ERROR	synchronizer/synchronizer.go:706	error: mismatched leaf count: 94446, expected: 94447
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
/src/synchronizer/synchronizer.go:706 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:706
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:13.366Z	WARN	synchronizer/synchronizer.go:458	error syncing blocks: mismatched leaf count: 94446, expected: 94447	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:458
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:13.366Z	INFO	synchronizer/synchronizer.go:474	L1 state fully synchronized	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.392Z	INFO	synchronizer/synchronizer.go:404	latestSequencedBatchNumber: 501068, latestSyncedBatch: 492348, lastVerifiedBatchNumber: 501028	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.392Z	INFO	synchronizer/synchronizer.go:453	Syncing L1 blocks sequentially lastEthBlockSynced=5711827	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.438Z	INFO	synchronizer/synchronizer.go:812	[checkReorg function] BlockNumber: 5711827 BlockHash got from L1 provider: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.439Z	INFO	synchronizer/synchronizer.go:813	[checkReorg function] latestBlockNumber: 5711827 latestBlockHash already synced: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.439Z	INFO	synchronizer/synchronizer.go:582	Syncing block 5711828 of 5731646	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.439Z	INFO	synchronizer/synchronizer.go:583	Getting rollup info from block 5711828 to block 5711928	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.538Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0xf1bd543ba8ed4e9b297beb767af12f5260ad31416c2597fa9d0b4475abbe41a1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:13.540Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492349 492350 492351 492352 492353 492354 492355 492356 492357 492358 492359 492360 492361 492362 492363 492364 492365 492366 492367 492368]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:14.192Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x76938bbe53960b82667c1ca966df5577bfec361d3afad71fd4cb231c1ff153a9, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:14.193Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492369 492370 492371 492372 492373 492374 492375 492376 492377 492378 492379 492380 492381 492382 492383 492384 492385 492386 492387 492388]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:15.332Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x09b69c728c38bb8abef60243fac35b30dab4b08af4de37c9c741dc63566ddcf1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:15.359Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492389 492390 492391 492392 492393 492394 492395 492396 492397 492398 492399 492400 492401 492402 492403 492404 492405 492406 492407 492408]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.147Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x69e2dde20b28b558e1cfc02256e994e0d9a7e636810d27d6f63484915725adde, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.149Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492409 492410 492411 492412 492413 492414 492415 492416 492417 492418 492419 492420 492421 492422 492423 492424 492425 492426 492427 492428]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.571Z	INFO	synchronizer/synchronizer.go:812	[checkReorg function] BlockNumber: 5711827 BlockHash got from L1 provider: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.571Z	INFO	synchronizer/synchronizer.go:813	[checkReorg function] latestBlockNumber: 5711827 latestBlockHash already synced: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.572Z	ERROR	state/l1infotree.go:73	error add new leaf to the L1InfoTree. Error: mismatched leaf count: 94446, expected: 94447
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
/src/state/l1infotree.go:73 github.com/0xPolygonHermez/zkevm-node/state.(*State).AddL1InfoTreeLeaf()
/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:47 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process()
/src/synchronizer/actions/processor_manager/processor_manager.go:66 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process()
/src/synchronizer/synchronizer.go:704 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/state.(*State).AddL1InfoTreeLeaf
	/src/state/l1infotree.go:73
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process
	/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:47
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:17.572Z	ERROR	etrog/processor_l1_info_tree_update.go:49	error storing the l1InfoTree(etrog). BlockNumber: 5711829, error: mismatched leaf count: 94446, expected: 94447%!(EXTRA string=
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:251 github.com/0xPolygonHermez/zkevm-node/log.Errorf()
/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:49 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process()
/src/synchronizer/actions/processor_manager/processor_manager.go:66 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process()
/src/synchronizer/synchronizer.go:704 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
)	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process
	/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:49
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:17.572Z	ERROR	synchronizer/synchronizer.go:706	error: mismatched leaf count: 94446, expected: 94447
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
/src/synchronizer/synchronizer.go:706 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:706
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:17.572Z	WARN	synchronizer/synchronizer.go:458	error syncing blocks: mismatched leaf count: 94446, expected: 94447	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:458
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:17.572Z	INFO	synchronizer/synchronizer.go:474	L1 state fully synchronized	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.628Z	INFO	synchronizer/synchronizer.go:404	latestSequencedBatchNumber: 501068, latestSyncedBatch: 492348, lastVerifiedBatchNumber: 501028	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.628Z	INFO	synchronizer/synchronizer.go:453	Syncing L1 blocks sequentially lastEthBlockSynced=5711827	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.677Z	INFO	synchronizer/synchronizer.go:812	[checkReorg function] BlockNumber: 5711827 BlockHash got from L1 provider: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.677Z	INFO	synchronizer/synchronizer.go:813	[checkReorg function] latestBlockNumber: 5711827 latestBlockHash already synced: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.677Z	INFO	synchronizer/synchronizer.go:582	Syncing block 5711828 of 5731646	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.677Z	INFO	synchronizer/synchronizer.go:583	Getting rollup info from block 5711828 to block 5711928	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.781Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0xf1bd543ba8ed4e9b297beb767af12f5260ad31416c2597fa9d0b4475abbe41a1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:17.783Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492349 492350 492351 492352 492353 492354 492355 492356 492357 492358 492359 492360 492361 492362 492363 492364 492365 492366 492367 492368]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:19.503Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x76938bbe53960b82667c1ca966df5577bfec361d3afad71fd4cb231c1ff153a9, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:19.505Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492369 492370 492371 492372 492373 492374 492375 492376 492377 492378 492379 492380 492381 492382 492383 492384 492385 492386 492387 492388]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:20.190Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x09b69c728c38bb8abef60243fac35b30dab4b08af4de37c9c741dc63566ddcf1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:20.191Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492389 492390 492391 492392 492393 492394 492395 492396 492397 492398 492399 492400 492401 492402 492403 492404 492405 492406 492407 492408]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:21.468Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x69e2dde20b28b558e1cfc02256e994e0d9a7e636810d27d6f63484915725adde, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:21.482Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492409 492410 492411 492412 492413 492414 492415 492416 492417 492418 492419 492420 492421 492422 492423 492424 492425 492426 492427 492428]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:22.945Z	INFO	synchronizer/synchronizer.go:812	[checkReorg function] BlockNumber: 5711827 BlockHash got from L1 provider: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:22.945Z	INFO	synchronizer/synchronizer.go:813	[checkReorg function] latestBlockNumber: 5711827 latestBlockHash already synced: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:22.946Z	ERROR	state/l1infotree.go:73	error add new leaf to the L1InfoTree. Error: mismatched leaf count: 94446, expected: 94447
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
/src/state/l1infotree.go:73 github.com/0xPolygonHermez/zkevm-node/state.(*State).AddL1InfoTreeLeaf()
/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:47 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process()
/src/synchronizer/actions/processor_manager/processor_manager.go:66 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process()
/src/synchronizer/synchronizer.go:704 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/state.(*State).AddL1InfoTreeLeaf
	/src/state/l1infotree.go:73
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process
	/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:47
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:22.946Z	ERROR	etrog/processor_l1_info_tree_update.go:49	error storing the l1InfoTree(etrog). BlockNumber: 5711829, error: mismatched leaf count: 94446, expected: 94447%!(EXTRA string=
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:251 github.com/0xPolygonHermez/zkevm-node/log.Errorf()
/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:49 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process()
/src/synchronizer/actions/processor_manager/processor_manager.go:66 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process()
/src/synchronizer/synchronizer.go:704 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
)	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process
	/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:49
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:22.946Z	ERROR	synchronizer/synchronizer.go:706	error: mismatched leaf count: 94446, expected: 94447
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
/src/synchronizer/synchronizer.go:706 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:706
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:22.946Z	WARN	synchronizer/synchronizer.go:458	error syncing blocks: mismatched leaf count: 94446, expected: 94447	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:458
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:22.946Z	INFO	synchronizer/synchronizer.go:474	L1 state fully synchronized	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:22.972Z	INFO	synchronizer/synchronizer.go:404	latestSequencedBatchNumber: 501068, latestSyncedBatch: 492348, lastVerifiedBatchNumber: 501028	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:22.972Z	INFO	synchronizer/synchronizer.go:453	Syncing L1 blocks sequentially lastEthBlockSynced=5711827	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:23.017Z	INFO	synchronizer/synchronizer.go:812	[checkReorg function] BlockNumber: 5711827 BlockHash got from L1 provider: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:23.017Z	INFO	synchronizer/synchronizer.go:813	[checkReorg function] latestBlockNumber: 5711827 latestBlockHash already synced: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:23.017Z	INFO	synchronizer/synchronizer.go:582	Syncing block 5711828 of 5731646	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:23.017Z	INFO	synchronizer/synchronizer.go:583	Getting rollup info from block 5711828 to block 5711928	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:23.119Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0xf1bd543ba8ed4e9b297beb767af12f5260ad31416c2597fa9d0b4475abbe41a1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:23.120Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492349 492350 492351 492352 492353 492354 492355 492356 492357 492358 492359 492360 492361 492362 492363 492364 492365 492366 492367 492368]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:24.743Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x76938bbe53960b82667c1ca966df5577bfec361d3afad71fd4cb231c1ff153a9, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:24.745Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492369 492370 492371 492372 492373 492374 492375 492376 492377 492378 492379 492380 492381 492382 492383 492384 492385 492386 492387 492388]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:26.394Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x09b69c728c38bb8abef60243fac35b30dab4b08af4de37c9c741dc63566ddcf1, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:26.396Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492389 492390 492391 492392 492393 492394 492395 492396 492397 492398 492399 492400 492401 492402 492403 492404 492405 492406 492407 492408]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:28.107Z	INFO	etherman/etherman_xlayer.go:1239	tx hash: 0x69e2dde20b28b558e1cfc02256e994e0d9a7e636810d27d6f63484915725adde, msg form:0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6, to:0x01469dACfDDA885D68Ff0f8628F2629c14F95a20	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:28.109Z	INFO	dataavailability/dataavailability.go:73	Try to get data from trusted sequencer for batches [492409 492410 492411 492412 492413 492414 492415 492416 492417 492418 492419 492420 492421 492422 492423 492424 492425 492426 492427 492428]	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:28.906Z	INFO	synchronizer/synchronizer.go:812	[checkReorg function] BlockNumber: 5711827 BlockHash got from L1 provider: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:28.906Z	INFO	synchronizer/synchronizer.go:813	[checkReorg function] latestBlockNumber: 5711827 latestBlockHash already synced: 0xae440697b90917ea47fb106f4df69e794a78842cc66ea7a73f0ea046aca1e38a	{"pid": 1, "version": "v0.3.6-5-g76857189"}
2024-04-19T12:33:28.907Z	ERROR	state/l1infotree.go:73	error add new leaf to the L1InfoTree. Error: mismatched leaf count: 94446, expected: 94447
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
/src/state/l1infotree.go:73 github.com/0xPolygonHermez/zkevm-node/state.(*State).AddL1InfoTreeLeaf()
/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:47 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process()
/src/synchronizer/actions/processor_manager/processor_manager.go:66 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process()
/src/synchronizer/synchronizer.go:704 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/state.(*State).AddL1InfoTreeLeaf
	/src/state/l1infotree.go:73
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process
	/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:47
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:28.907Z	ERROR	etrog/processor_l1_info_tree_update.go:49	error storing the l1InfoTree(etrog). BlockNumber: 5711829, error: mismatched leaf count: 94446, expected: 94447%!(EXTRA string=
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:251 github.com/0xPolygonHermez/zkevm-node/log.Errorf()
/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:49 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process()
/src/synchronizer/actions/processor_manager/processor_manager.go:66 github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process()
/src/synchronizer/synchronizer.go:704 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
)	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/etrog.(*ProcessorL1InfoTreeUpdate).Process
	/src/synchronizer/actions/etrog/processor_l1_info_tree_update.go:49
github.com/0xPolygonHermez/zkevm-node/synchronizer/actions/processor_manager.(*L1EventProcessors).Process
	/src/synchronizer/actions/processor_manager/processor_manager.go:66
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:704
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:28.907Z	ERROR	synchronizer/synchronizer.go:706	error: mismatched leaf count: 94446, expected: 94447
/src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
/src/synchronizer/synchronizer.go:706 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange()
/src/synchronizer/synchronizer.go:612 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
/src/synchronizer/synchronizer.go:454 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:356 main.runSynchronizer()
	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).ProcessBlockRange
	/src/synchronizer/synchronizer.go:706
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
	/src/synchronizer/synchronizer.go:612
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:454
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:28.907Z	WARN	synchronizer/synchronizer.go:458	error syncing blocks: mismatched leaf count: 94446, expected: 94447	{"pid": 1, "version": "v0.3.6-5-g76857189"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:458
main.runSynchronizer
	/src/cmd/run.go:356
2024-04-19T12:33:28.907Z	INFO	synchronizer/synchronizer.go:474	L1 state fully synchronized	{"pid": 1, "version": "v0.3.6-5-g76857189"}


```

### PR DESCRIPTION
**Pull request by ARR552**
Closes #3573

### What does this PR do?

This PR fixes the issue found by okx team regarding a problem with l1info tree if the process information function returns an error. 

### Reviewers

- @joanestebanr 
- @tclemos

### CODE REVIEW

File: config/default.go [hunk 1]
```diff
@@ -104,7 +104,7 @@ SyncChunkSize = 100
 TrustedSequencerURL = "" # If it is empty or not specified, then the value is read from the smc
 SyncBlockProtection = "safe" # latest, finalized, safe
 L1SynchronizationMode = "sequential"
-L1SyncCheckL2BlockHash = true
+L1SyncCheckL2BlockHash = false
```
Comment (joanestebanr) [inline config/default.go]: What is the reason of disabling the check?

Comment (ARR552) [reply config/default.go]: to disable disable by default the problematic and not beneficial check that I suggested to remove in this other PR https://github.com/0xPolygonHermez/zkevm-node/pull/3575

**Review by joanestebanr — APPROVED** [review]
