### PR TITLE
fix: fixing forced batches error handling and normal batches transaction level error handling.

### LINKED ISSUE #2099: Fix error handling in OOC for forced batches
finalize.go line 660

```
if err != nil || !response.IsBatchProcessed {
  f.halt(ctx, fmt.Errorf("failed to process forced batch, Executor err: %w", err))
  return lastBatchNumberInState, stateRoot
}
```

In case of OOC err is nill and it is unclear in the logs

### PR DESCRIPTION
**Pull request by Psykepro**
Closes #2099.

### What does this PR do?

Fixing:
- The full `error handling` for `Forced Batches`.
- The `transaction level error handling` for `Normal Batches`.
- The case for parsing`ErrIntrinsicInvalidBatchGasLimit` in `RomErrorCode` function of the state

### Reviewers

Main reviewers:
- @ToniRamirezM 
- @krlosMata 
- @ARR552 

Codeowner reviewers:
- @ToniRamirezM

### CODE REVIEW

**Review by ToniRamirezM — APPROVED** [review]

File: sequencer/finalizer.go [hunk 1]
```diff
@@ -399,7 +398,8 @@ func (f *finalizer) processTransaction(ctx context.Context, tx *TxTracker) error
 // handleTxProcessResp handles the response of transaction processing.
 func (f *finalizer) handleTxProcessResp(ctx context.Context, tx *TxTracker, result *state.ProcessBatchResponse, oldStateRoot common.Hash) error {
 	// Handle Transaction Error
-	if result.Responses[0].RomError != nil && !errors.Is(result.Responses[0].RomError, runtime.ErrExecutionReverted) {
+	if !result.IsBatchProcessed {
+		// If intrinsic error or OOC error, we skip adding the transaction to the batch
 		f.handleTransactionError(ctx, result, tx)
 		return result.Responses[0].RomError
```
Comment (ARR552) [inline sequencer/finalizer.go:404]: Why returning thefirst response?

File: sequencer/finalizer.go [hunk 2]
```diff
@@ -667,11 +676,7 @@ func (f *finalizer) processForcedBatch(ctx context.Context, lastBatchNumberInSta
 	f.nextGERMux.Lock()
 	f.lastGERHash = forcedBatch.GlobalExitRoot
 	f.nextGERMux.Unlock()
-
-	err = f.handleForcedBatchProcessResp(request, response, stateRoot)
-	if err != nil {
-		return lastBatchNumberInState, stateRoot
-	}
+	_ = f.handleForcedTxsProcessResp(request, response, stateRoot)
```
Comment (ARR552) [inline sequencer/finalizer.go:679]: why do we ignore the error?

File: sequencer/finalizer.go [hunk 3]
```diff
@@ -418,22 +418,30 @@ func (f *finalizer) handleTxProcessResp(ctx context.Context, tx *TxTracker, resu
...
+func (f *finalizer) handleForcedTxsProcessResp(request state.ProcessRequest, result *state.ProcessBatchResponse, oldStateRoot common.Hash) error {
+	log.Infof("handleForcedTxsProcessResp: batchNumber: %d, oldStateRoot: %s, newStateRoot: %s", request.BatchNumber, oldStateRoot.String(), result.NewStateRoot.String())
 	for _, txResp := range result.Responses {
 		// Handle Transaction Error
-		if txResp.RomError != nil && !errors.Is(txResp.RomError, runtime.ErrExecutionReverted) {
-			errorCode := executor.RomErrorCode(txResp.RomError)
-			if executor.IsROMOutOfCountersError(errorCode) {
-				log.Warnf("handleForcedBatchProcessResp: ROM out of counters error: %s", txResp.RomError)
+		romErr := executor.RomErrorCode(txResp.RomError)
+		if txResp.RomError != nil {
```
Comment (ARR552) [inline sequencer/finalizer.go:427]:
```suggestion
		if txResp.RomError != nil {
		      romErr := executor.RomErrorCode(txResp.RomError)

```

File: sequencer/finalizer.go [hunk 4]
```diff
@@ -418,22 +418,30 @@ func (f *finalizer) handleTxProcessResp(ctx context.Context, tx *TxTracker, resu
...
+			if executor.IsROMOutOfCountersError(romErr) {
+				// If we are out of counters, we should stop processing the batch
+				log.Errorf("handleForcedTxsProcessResp: ROM error: %s", txResp.RomError)
 				return txResp.RomError
+			} else if executor.IsIntrinsicError(romErr) {
+				// If we have an intrinsic error, we should continue processing the batch, but skip the transaction
+				if txResp.RomError != nil {
```
Comment (ARR552) [inline sequencer/finalizer.go:434]: I think this is redundant

**Review by ARR552 — CHANGES_REQUESTED** [review]
What about the list of errors that increase the nonce??

File: sequencer/finalizer.go (hunk 4 above)
Comment (Psykepro) [reply sequencer/finalizer.go:434]: it is not as if we skip adding the tx to the db if we have intrinsic error

File: sequencer/finalizer.go (hunk 2 above)
Comment (Psykepro) [reply sequencer/finalizer.go:679]: because nothing happens even if we have error the I can just remove returning it

Comment (Psykepro) [reply sequencer/finalizer.go:679]: because nothing happens even if we have error I can just remove returning it

File: sequencer/finalizer.go (hunk 1 above)
Comment (Psykepro) [reply sequencer/finalizer.go:404]: Here we process 1 by 1 we always can have only 1 response

**Review by ARR552 — APPROVED** [review]

**Review by krlosMata — APPROVED** [review]
:smile_cat:
