### PR TITLE
fix closing batch + logs

### LINKED ISSUE #2347: error closing batch issue

### PR DESCRIPTION
**Pull request by ARR552**
Closes #2347

### What does this PR do?

This PR fixes the closing batch error during the trusted state synchronization
### Reviewers

- @joanestebanr 
- @ToniRamirezM

### CODE REVIEW

File: synchronizer/synchronizer.go [hunk 1]
```diff
@@ -1348,6 +1371,10 @@ func (s *ClientSynchronizer) processTrustedBatch(trustedBatch *types.Batch, dbTx
 				log.Warnf("CASE 01: the batch [%d] looks like were not close but in STATE was closed", trustedBatch.Number)
```
Comment (ToniRamirezM) [inline synchronizer/synchronizer.go]:
```suggestion
				log.Warnf("CASE 01: batch [%d] was not closed but in was closed in STATE", trustedBatch.Number)
```

File: synchronizer/synchronizer.go [hunk 2]
```diff
@@ -1291,6 +1291,29 @@ func (s *ClientSynchronizer) processTrustedBatch(trustedBatch *types.Batch, dbTx
 							return nil, nil, err
 						} else {
 							log.Warnf("CASE 02: the batch [%d] looks like were not close but in STATE was closed", trustedBatch.Number)
```
Comment (ToniRamirezM) [inline synchronizer/synchronizer.go]:
```suggestion
							log.Warnf("CASE 02: batch [%d] was not closed but in was closed in STATE", trustedBatch.Number)
```

**Review by ToniRamirezM — CHANGES_REQUESTED** [review]

File: synchronizer/synchronizer.go [hunk 3]
```diff
@@ -1251,8 +1251,22 @@ func (s *ClientSynchronizer) processTrustedBatch(trustedBatch *types.Batch, dbTx
 
 		// Find txs to be processed and included in the trusted state
 		if *s.trustedState.lastStateRoot == batches[1].StateRoot {
+			// Delete txs that were stored before restart. We need to reprocess all txs because the intermediary stateRoot is only store in memory
```
Comment (ToniRamirezM) [inline synchronizer/synchronizer.go]:
```suggestion
			// Delete txs that were stored before restart. We need to reprocess all txs because the intermediary stateRoot is only stored in memory
```

**Review by ToniRamirezM — CHANGES_REQUESTED** [review]

**Review by ToniRamirezM — APPROVED** [review]
