### PR TITLE
etrog: Fix synchronizer  OOC sequenced batch

### LINKED ISSUE #3098: Accept sequenced batches with Out Of Counters error
#### System information

zkEVM Node version: `v0.0.5-RC15`
Network: `devnet-etrog`

#### Expected behaviour
A Sequenced batch with Out Of Counters error (OOC) must be stored empty with no L2Block

#### Actual behaviour
It provoke a reorg

### PR DESCRIPTION
**Pull request by joanestebanr**
close #3098 
### What does this PR do?
- Fix OOC sequenced batch reorg
- Refactor interfaces to do unittest to l1 sequencer process

### Reviewers

Main reviewers:

- @ARR552

### CODE REVIEW

File: state/batchV2.go [hunk 1]
```diff
@@ -406,7 +408,7 @@ func (s *State) ProcessAndStoreClosedBatchV2(ctx context.Context, processingCtx
 	}
 	if processedBatch.IsRomOOCError {
 		log.Errorf("%s error isRomOOCError: %v", debugPrefix, err)
-		return common.Hash{}, noFlushID, noProverID, ErrExecutingBatchOOC
+		//	return common.Hash{}, noFlushID, noProverID, ErrExecutingBatchOOC
```
Comment (ARR552) [inline state/batchV2.go]: can you remove the used code?

File: state/convertersV2.go [hunk 2]
```diff
@@ -33,7 +33,7 @@ func (s *State) convertToProcessBatchResponseV2(batchResponse *executor.ProcessB
 	if err != nil {
 		return nil, err
 	}
-
+	isRomOOCError = isRomOOCError || executor.IsROMOutOfCountersError(batchResponse.ErrorRom)
```
Comment (ARR552) [inline state/convertersV2.go:36]: is rom error the same as oocError? Maybe @ToniRamirezM can answere

Comment (ToniRamirezM) [reply state/convertersV2.go:36]: There are 34 different ROM errors, only 7 of them are OOC.

**Review by ToniRamirezM — APPROVED** [review]
