### PR TITLE
improve: making the timeout of the RPC server to be configurable and fixing deprecated func for creating temp file.

### LINKED ISSUE #614: Timeout for the RPC server should be configurable
Right now it's constant at one second

### PR DESCRIPTION
**Pull request by Psykepro**
Signed-off-by: Nikolay Nedkov <nikolai_nedkov@yahoo.com>

Closes #614 .

### What does this PR do?

Making the `ReadTimeout` and `WriteTimeout` of the `RPC HTTP Server` to be configurable by expecting values in the `config file` in seconds with the following names:
`ReadTimeoutInSec`
`WriteTimeoutInSec`

And fixing deprecated function use in `config.go` for creating temp file.

### Reviewers

- @KonradIT 
- @kind84 
- @tclemos 
- @ARR552 

Main reviewers:

- @KonradIT 
- @kind84

### CODE REVIEW

File: config/config_test.go [hunk 1]
```diff
@@ -268,7 +275,7 @@ func Test_Defaults(t *testing.T) {
 			expectedValue: 61090,
 		},
 	}
-	file, err := ioutil.TempFile("", "genesisConfig")
+	file, err := os.CreateTemp("", "genesisConfig")
```
Comment (ARR552) [inline config/config_test.go:278]: why do you think is better os.CreateTemp vs ioutil.TempFile??

File: config/default.go [hunk 2]
```diff
@@ -47,6 +47,8 @@ PercentageToIncreaseGasLimit = 10
 [RPC]
 Host = "0.0.0.0"
 Port = 8123
+ReadTimeoutInSec = 1
+WriteTimeoutInSec = 1
```
Comment (ARR552) [inline config/default.go:51]: this values configured seems too short

File: config/config_test.go (hunk 1 above)
Comment (Psykepro) [reply config/config_test.go:278]: because the ioutil.TempFile is deprecated from go 1.17:
image

:)

**Review by ToniRamirezM — APPROVED** [review]

**Review by kind84 — APPROVED** [review]
LGTM :ok_hand:
