### PR TITLE
fix sync_info table

### LINKED ISSUE #1918: Populate table `sync_info`

### PR DESCRIPTION
**Pull request by ARR552**
Closes #1918

### What does this PR do?

This adds the missing information to the table  sync_info

### Reviewers

- @arnaubennassar 
- @tclemos

### CODE REVIEW

**Review by tclemos — APPROVED** [review]

File: synchronizer/synchronizer.go [hunk 1]
```diff
@@ -136,7 +191,24 @@ func (s *ClientSynchronizer) Sync() error {
...
+				continue
+			}
+
+			// Check the latest verified Batch number in the smc
+			lastVerifiedBatchNumber, err := s.etherMan.GetLatestVerifiedBatchNum()
+			if err != nil {
+				log.Warn("error getting last verified batch in the rollup. Error: ", err)
+				continue
+			}
+			err = s.state.SetLastBatchNumberVerifiedOnEthereum(s.ctx, lastVerifiedBatchNumber, nil)
```
Comment (arnaubennassar) [inline synchronizer/synchronizer.go:209]: Consider merging the two inserts:
- SetLastBatchNumberSeenOnEthereum
- SetLastBatchNumberVerifiedOnEthereum
into `SetLastBatchInfoSeenOnEthereum`.

**Review by arnaubennassar — CHANGES_REQUESTED** [review]

File: synchronizer/synchronizer.go (hunk 1 above)
Comment (tclemos) [reply synchronizer/synchronizer.go:209]: why?

Comment (ARR552) [reply synchronizer/synchronizer.go]: mmm no, thats not possible. LastBatchSeenOnEThereum is the virtual state, and the other is the consolidated state. Both are completely different steps. We couldn't differentiate between them

**Review by arnaubennassar — APPROVED** [review]
