### PR TITLE
New Logs and fix to GER Closing Signal

### LINKED ISSUE #1869: Update and activate ClosingSignalsManagerTest

### PR DESCRIPTION
**Pull request by ToniRamirezM**
Closes #1869

### What does this PR do?

Fixes a log in the sequencer.

### Reviewers

Main reviewers:

- @arnaubennassar 
- @Psykepro 
- @agnusmor

### CODE REVIEW

File: sequencer/closingsignalsmanager.go [hunk 1]
```diff
@@ -55,13 +57,25 @@ func (c *closingSignalsManager) checkGERUpdate() {
 	for {
 		time.Sleep(c.cfg.ClosingSignalsManagerWaitForCheckingGER.Duration)
 
-		ger, _, err := c.dbManager.GetLatestGer(c.ctx, c.cfg.GERFinalityNumberOfBlocks)
+		lastL1BlockNumber, err := c.etherman.GetLatestBlockNumber(c.ctx)
+		if err != nil {
+			log.Errorf("error checking GER update: %v", err)
+			continue
```
Comment (tclemos) [inline sequencer/closingsignalsmanager.go:63]: It would be good to change this message avoid confusing it with line 73

File: sequencer/closingsignalsmanager_test.go
Comment (tclemos) [inline sequencer/closingsignalsmanager_test.go:1]: What's the plan for this commented test?

Comment (ToniRamirezM) [reply sequencer/closingsignalsmanager_test.go:1]: I created and issue. This has been done directly on mainnet so no time today to do it.

File: sequencer/closingsignalsmanager.go (hunk 1 above)
Comment (ToniRamirezM) [reply sequencer/closingsignalsmanager.go]: Changed

**Review by tclemos — APPROVED** [review]

**Review by ARR552 — APPROVED** [review]
