### PR TITLE
[Aggregator] Add recovery mechanism for stuck proofs

### LINKED ISSUE #1516: [Aggregator] Recover proof status from failure
On public testnet we faced a couple of situations in which we were not able to pick up a proof that was laying in the database. 
This caused all subsequent proofs to pile up and verifications stopped.
Sometimes the workaround was rebooting the Aggregator, causing it to clear al "pending" proofs (aka `generating = true`) and start over again. But in other occasions this wasn't enough. We had to manually delete the record from the database.

Here are the logs showing what happened:
```
2023-01-04T14:43:30Z	[33mWARN[0m	aggregator/aggregator.go:434	Failed to begin transaction to release proof aggregation state, err: unexpected EOF
2023-01-04T14:43:30Z	[31mERROR[0m	aggregator/aggregator.go:513	Failed to release aggregated proofs, err: unexpected EOF%!(EXTRA string=
2023-01-04T14:43:30Z	[31mERROR[0m	aggregator/aggregator.go:175	Error trying to aggregate proofs: Failed to begin transaction to update proof aggregation state unexpected EOF%!(EXTRA string=
2023-01-04T14:43:30Z	[31mERROR[0m	aggregator/aggregator.go:180	Error trying to generate proof: failed to connect to `host=zkevmpublic2corestatedb.cluster-cirmnf3qsupn.eu-west-1.rds.amazonaws.com user=zkevmpublic2corestatedb database=zkevmpublic2corestatedb`: dial error (dial tcp 10.30.7.148:5432: connect: connection refused)%!(EXTRA string=
```
In this case there was an error aggregating proofs and the rollback failed.
Side note: the log of the original error is missing because in the code we are trapping the error in a defer function without logging it before. Then another error occurred in the defer and we see the log for this one.
The source of the problem here was the database dropping connections due to high cpu load.

Another scenario:
<details>
  <summary>Click to expand the logs</summary>

```
2023-01-05T12:38:48.686Z |   | "zkevm-public2" | 2023-01-05T12:38:48Z	[34mINFO[0m	aggregator/aggregator.go:621	Checking profitability to aggregate batch, batchNumber: 38766
-- | -- | -- | --
2023-01-05T12:38:48.686Z |   | "zkevm-public2" | 2023-01-05T12:38:48Z	[34mINFO[0m	aggregator/aggregator.go:619	Found virtual batch 38766 pending to generate proof
2023-01-05T12:38:48.671Z |   | "zkevm-public2" | 2023-01-05T12:38:48Z	[35mDEBUG[0m	aggregator/aggregator.go:654	tryGenerateBatchProof start prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] }
2023-01-05T12:38:48.671Z |   | "zkevm-public2" | 2023-01-05T12:38:48Z	[35mDEBUG[0m	aggregator/aggregator.go:500	Nothing to aggregate
2023-01-05T12:38:48.665Z |   | "zkevm-public2" | 2023-01-05T12:38:48Z	[35mDEBUG[0m	aggregator/aggregator.go:495	tryAggregateProofs start prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] }
2023-01-05T12:38:48.665Z |   | "zkevm-public2" | 2023-01-05T12:38:48Z	[35mDEBUG[0m	aggregator/aggregator.go:306	Time to verify proof not reached
2023-01-05T12:38:48.665Z |   | "zkevm-public2" | 2023-01-05T12:38:48Z	[35mDEBUG[0m	aggregator/aggregator.go:303	tryBuildFinalProof start prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] }
2023-01-05T12:38:48.329Z |   | "zkevm-public2" | 2023-01-05T12:38:48Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:38:43.663Z |   | "zkevm-public2" | 2023-01-05T12:38:43Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:38:43.285Z |   | "zkevm-public2" | 2023-01-05T12:38:43Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:38:38.661Z |   | "zkevm-public2" | 2023-01-05T12:38:38Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:38:38.284Z |   | "zkevm-public2" | 2023-01-05T12:38:38Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:38:33.629Z |   | "zkevm-public2" | 2023-01-05T12:38:33Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:38:33.206Z |   | "zkevm-public2" | 2023-01-05T12:38:33Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:38:28.627Z |   | "zkevm-public2" | 2023-01-05T12:38:28Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:38:28.143Z |   | "zkevm-public2" | 2023-01-05T12:38:28Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:38:23.553Z |   | "zkevm-public2" | 2023-01-05T12:38:23Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:38:23.101Z |   | "zkevm-public2" | 2023-01-05T12:38:23Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:38:18.551Z |   | "zkevm-public2" | 2023-01-05T12:38:18Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:38:18.051Z |   | "zkevm-public2" | 2023-01-05T12:38:18Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:38:13.463Z |   | "zkevm-public2" | 2023-01-05T12:38:13Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:38:13.007Z |   | "zkevm-public2" | 2023-01-05T12:38:13Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:38:08.461Z |   | "zkevm-public2" | 2023-01-05T12:38:08Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:38:07.962Z |   | "zkevm-public2" | 2023-01-05T12:38:07Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:38:03.416Z |   | "zkevm-public2" | 2023-01-05T12:38:03Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:38:02.865Z |   | "zkevm-public2" | 2023-01-05T12:38:02Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:58.415Z |   | "zkevm-public2" | 2023-01-05T12:37:58Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:57.853Z |   | "zkevm-public2" | 2023-01-05T12:37:57Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:53.372Z |   | "zkevm-public2" | 2023-01-05T12:37:53Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:52.851Z |   | "zkevm-public2" | 2023-01-05T12:37:52Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:48.370Z |   | "zkevm-public2" | 2023-01-05T12:37:48Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:47.809Z |   | "zkevm-public2" | 2023-01-05T12:37:47Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:44.385Z |   | "zkevm-public2" | 2023-01-05T12:37:44Z	[34mINFO[0m	broadcast/server.go:52	Server listening in "0.0.0.0:61090"
2023-01-05T12:37:44.384Z |   | "zkevm-public2" | 2023-01-05T12:37:44Z	[34mINFO[0m	cmd/run.go:106	Running broadcast service
2023-01-05T12:37:44.384Z |   | "zkevm-public2" | 2023-01-05T12:37:44Z	[34mINFO[0m	merkletree/client.go:27	connected to merkletree
2023-01-05T12:37:44.381Z |   | "zkevm-public2" | 2023-01-05T12:37:44Z	[34mINFO[0m	merkletree/client.go:22	trying to connect to merkletree: statedb.zkevm-public2.local:50061
2023-01-05T12:37:44.381Z |   | "zkevm-public2" | 2023-01-05T12:37:44Z	[34mINFO[0m	executor/client.go:44	connected to executor
2023-01-05T12:37:44.379Z |   | "zkevm-public2" | 2023-01-05T12:37:44Z	[34mINFO[0m	executor/client.go:33	trying to connect to executor: executor.zkevm-public2.local:50071
2023-01-05T12:37:44.379Z |   | "zkevm-public2" | 2023-01-05T12:37:44Z	[34mINFO[0m	cmd/run.go:74	Chain ID read from POE SC = 1422
2023-01-05T12:37:44.019Z |   | "zkevm-public2" | 2023-01-05T12:37:44Z	[34mINFO[0m	cmd/run.go:272	addr: 0x4756bC913ea1f59E8c046D53E09e8Cb6191D4d9e
2023-01-05T12:37:43.763Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[34mINFO[0m	aggregator/aggregator.go:703	Proof ID for batch 38765: 7b50d445-58dd-44c4-b5f2-b231e7172d72
2023-01-05T12:37:43.760Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[34mINFO[0m	aggregator/aggregator.go:693	Sending a batch to the prover. OldStateRoot [0xb42bea8650c083c1226ccee9d3825a84ca708817abd55f0efc4da1b3ca3efef3], OldBatchNum [38764]
2023-01-05T12:37:43.757Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[34mINFO[0m	aggregator/aggregator.go:680	Sending zki + batch to the prover, batchNumber [38765]
2023-01-05T12:37:43.757Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[34mINFO[0m	aggregator/aggregator.go:678	Prover { ID [d6e3433e-3920-4862-a533-f71a200d190e], addr [10.30.5.79:4036] } is going to be used to generate proof from batch [38765]
2023-01-05T12:37:43.752Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[34mINFO[0m	aggregator/aggregator.go:621	Checking profitability to aggregate batch, batchNumber: 38765
2023-01-05T12:37:43.752Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[34mINFO[0m	aggregator/aggregator.go:619	Found virtual batch 38765 pending to generate proof
2023-01-05T12:37:43.731Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[35mDEBUG[0m	aggregator/aggregator.go:654	tryGenerateBatchProof start prover { ID [d6e3433e-3920-4862-a533-f71a200d190e], addr [10.30.5.79:4036] }
2023-01-05T12:37:43.731Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[35mDEBUG[0m	aggregator/aggregator.go:500	Nothing to aggregate
2023-01-05T12:37:43.718Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[35mDEBUG[0m	aggregator/aggregator.go:495	tryAggregateProofs start prover { ID [d6e3433e-3920-4862-a533-f71a200d190e], addr [10.30.5.79:4036] }
2023-01-05T12:37:43.718Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[35mDEBUG[0m	aggregator/aggregator.go:306	Time to verify proof not reached
2023-01-05T12:37:43.718Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[35mDEBUG[0m	aggregator/aggregator.go:303	tryBuildFinalProof start prover { ID [d6e3433e-3920-4862-a533-f71a200d190e], addr [10.30.5.79:4036] }
2023-01-05T12:37:43.717Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[35mDEBUG[0m	aggregator/aggregator.go:150	Establishing stream connection with prover ID [d6e3433e-3920-4862-a533-f71a200d190e], addr [10.30.5.79:4036]
2023-01-05T12:37:43.292Z |   | "zkevm-public2" | 2023-01-05T12:37:43Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:42.808Z |   | "zkevm-public2" | 2023-01-05T12:37:42Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:40.218Z |   | "zkevm-public2" | 2023-01-05T12:37:40Z	[34mINFO[0m	db/db.go:79	successfully ran 0 migrations
2023-01-05T12:37:40.104Z |   | "zkevm-public2" | 2023-01-05T12:37:40Z	[34mINFO[0m	cmd/main.go:88	Starting application [Commit Hash: 99689e1, Version: v0.1.0] ...
2023-01-05T12:37:38.251Z |   | "zkevm-public2" | 2023-01-05T12:37:38Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:37.763Z |   | "zkevm-public2" | 2023-01-05T12:37:37Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:33.250Z |   | "zkevm-public2" | 2023-01-05T12:37:33Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:32.759Z |   | "zkevm-public2" | 2023-01-05T12:37:32Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:28.115Z |   | "zkevm-public2" | 2023-01-05T12:37:28Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:27.707Z |   | "zkevm-public2" | 2023-01-05T12:37:27Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:23.905Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[34mINFO[0m	aggregator/aggregator.go:703	Proof ID for batch 38764: 5576f2f5-ed80-42e6-810e-85ca8f33eddc
2023-01-05T12:37:23.904Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[34mINFO[0m	aggregator/aggregator.go:693	Sending a batch to the prover. OldStateRoot [0x634da66235fc22a0b80156f29279b0bbebf6a826c5897b209fefbf0c676b756d], OldBatchNum [38763]
2023-01-05T12:37:23.903Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[34mINFO[0m	aggregator/aggregator.go:680	Sending zki + batch to the prover, batchNumber [38764]
2023-01-05T12:37:23.903Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[34mINFO[0m	aggregator/aggregator.go:678	Prover { ID [b93246c1-d6f6-477e-9f67-cf3671f8ac6e], addr [10.30.5.79:51060] } is going to be used to generate proof from batch [38764]
2023-01-05T12:37:23.867Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[34mINFO[0m	aggregator/aggregator.go:621	Checking profitability to aggregate batch, batchNumber: 38764
2023-01-05T12:37:23.867Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[34mINFO[0m	aggregator/aggregator.go:619	Found virtual batch 38764 pending to generate proof
2023-01-05T12:37:23.800Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[35mDEBUG[0m	aggregator/aggregator.go:654	tryGenerateBatchProof start prover { ID [b93246c1-d6f6-477e-9f67-cf3671f8ac6e], addr [10.30.5.79:51060] }
2023-01-05T12:37:23.800Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[35mDEBUG[0m	aggregator/aggregator.go:500	Nothing to aggregate
2023-01-05T12:37:23.797Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[35mDEBUG[0m	aggregator/aggregator.go:495	tryAggregateProofs start prover { ID [b93246c1-d6f6-477e-9f67-cf3671f8ac6e], addr [10.30.5.79:51060] }
2023-01-05T12:37:23.797Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[35mDEBUG[0m	aggregator/aggregator.go:306	Time to verify proof not reached
2023-01-05T12:37:23.796Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[35mDEBUG[0m	aggregator/aggregator.go:303	tryBuildFinalProof start prover { ID [b93246c1-d6f6-477e-9f67-cf3671f8ac6e], addr [10.30.5.79:51060] }
2023-01-05T12:37:23.796Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[35mDEBUG[0m	aggregator/aggregator.go:150	Establishing stream connection with prover ID [b93246c1-d6f6-477e-9f67-cf3671f8ac6e], addr [10.30.5.79:51060]
2023-01-05T12:37:23.113Z |   | "zkevm-public2" | 2023-01-05T12:37:23Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:22.705Z |   | "zkevm-public2" | 2023-01-05T12:37:22Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:17.970Z |   | "zkevm-public2" | 2023-01-05T12:37:17Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:17.704Z |   | "zkevm-public2" | 2023-01-05T12:37:17Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:12.967Z |   | "zkevm-public2" | 2023-01-05T12:37:12Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:12.654Z |   | "zkevm-public2" | 2023-01-05T12:37:12Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:07.964Z |   | "zkevm-public2" | 2023-01-05T12:37:07Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560] } is not idle
2023-01-05T12:37:07.964Z |   | "zkevm-public2" | 2023-01-05T12:37:07Z	[35mDEBUG[0m	aggregator/aggregator.go:150	Establishing stream connection with prover ID [62f7e044-ac13-45fe-9c24-35bbb6f8532a], addr [10.30.5.79:18560]
2023-01-05T12:37:07.652Z |   | "zkevm-public2" | 2023-01-05T12:37:07Z	[35mDEBUG[0m	aggregator/aggregator.go:163	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658] } is not idle
2023-01-05T12:37:07.651Z |   | "zkevm-public2" | 2023-01-05T12:37:07Z	[35mDEBUG[0m	aggregator/aggregator.go:150	Establishing stream connection with prover ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.5.79:4658]
2023-01-05T12:36:49.992Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[34mINFO[0m	aggregator/aggregator.go:703	Proof ID for batch 38763: d28bc028-65bf-4411-aaeb-0225d6e9e86b
2023-01-05T12:36:49.991Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[34mINFO[0m	aggregator/aggregator.go:693	Sending a batch to the prover. OldStateRoot [0x72c23f29d61ef1af674e75f4af0712a3a5d112f169198334189165c3c3799a42], OldBatchNum [38762]
2023-01-05T12:36:49.979Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[34mINFO[0m	aggregator/aggregator.go:680	Sending zki + batch to the prover, batchNumber [38763]
2023-01-05T12:36:49.979Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[34mINFO[0m	aggregator/aggregator.go:678	Prover { ID [5e19277b-adb6-40e6-82e2-9d2ff382e1d3], addr [10.30.5.79:8712] } is going to be used to generate proof from batch [38763]
2023-01-05T12:36:49.960Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[34mINFO[0m	aggregator/aggregator.go:621	Checking profitability to aggregate batch, batchNumber: 38763
2023-01-05T12:36:49.960Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[34mINFO[0m	aggregator/aggregator.go:619	Found virtual batch 38763 pending to generate proof
2023-01-05T12:36:49.910Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[35mDEBUG[0m	aggregator/aggregator.go:654	tryGenerateBatchProof start prover { ID [5e19277b-adb6-40e6-82e2-9d2ff382e1d3], addr [10.30.5.79:8712] }
2023-01-05T12:36:49.910Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[35mDEBUG[0m	aggregator/aggregator.go:500	Nothing to aggregate
2023-01-05T12:36:49.877Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[35mDEBUG[0m	aggregator/aggregator.go:495	tryAggregateProofs start prover { ID [5e19277b-adb6-40e6-82e2-9d2ff382e1d3], addr [10.30.5.79:8712] }
2023-01-05T12:36:49.877Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[35mDEBUG[0m	aggregator/aggregator.go:306	Time to verify proof not reached
2023-01-05T12:36:49.877Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[35mDEBUG[0m	aggregator/aggregator.go:303	tryBuildFinalProof start prover { ID [5e19277b-adb6-40e6-82e2-9d2ff382e1d3], addr [10.30.5.79:8712] }
2023-01-05T12:36:49.876Z |   | "zkevm-public2" | 2023-01-05T12:36:49Z	[35mDEBUG[0m	aggregator/aggregator.go:150	Establishing stream connection with prover ID [5e19277b-adb6-40e6-82e2-9d2ff382e1d3], addr [10.30.5.79:8712]
2023-01-05T12:35:53.122Z |   | "zkevm-public2" | 2023-01-05T12:35:53Z	[34mINFO[0m	aggregator/aggregator.go:703	Proof ID for batch 38762: dec7f2a9-9ed2-407f-acae-8956bb7466b0
2023-01-05T12:35:53.086Z |   | "zkevm-public2" | 2023-01-05T12:35:53Z	[34mINFO[0m	aggregator/aggregator.go:693	Sending a batch to the prover. OldStateRoot [0xcb9c9b06f9b83c46c8c17df52da38c7ec91df799b8fea37c9ef5d78a1b56cf5c], OldBatchNum [38761]
2023-01-05T12:35:53.081Z |   | "zkevm-public2" | 2023-01-05T12:35:53Z	[34mINFO[0m	aggregator/aggregator.go:680	Sending zki + batch to the prover, batchNumber [38762]
2023-01-05T12:35:53.081Z |   | "zkevm-public2" | 2023-01-05T12:35:53Z	[34mINFO[0m	aggregator/aggregator.go:678	Prover { ID [412ccc4e-a04c-485b-a903-c7dc6c4cda44], addr [10.30.4.68:47931] } is going to be used to generate proof from batch [38762]
2023-01-05T12:35:52.879Z |   | "zkevm-public2" | 2023-01-05T12:35:52Z	[34mINFO[0m	aggregator/aggregator.go:621	Checking profitability to aggregate batch, batchNumber: 38762
2023-01-05T12:35:52.878Z |   | "zkevm-public2" | 2023-01-05T12:35:52Z	[34mINFO[0m	aggregator/aggregator.go:619	Found virtual batch 38762 pending to generate proof
```
</details>

In this case a proof (for batch `388762`) was generating, but then the prover disconnected and all other provers started to look busy. Then the Aggregator restarted and after that the proof was stuck in the database.

Proper UTs in the Aggregator are required to avoid these situations.

### PR DESCRIPTION
**Pull request by kind84**
Closes #1516 .

### Background

There may be chances in which a proof under generation by a prover end up being lost (network failure, db failure, ...).
These proofs stays forever in our `proof` table because they looked to be reserved by a prover, thus the aggregator does not send them to other provers.
For this reason we needed a mechanism to clear those stuck proofs from the table.

### Proposal

This PR  introduces a new method in the `Aggregator` called `cleanupLockedProofs` that continuously checks for locked proofs in the table and if any it clears them out.
The frequency of this check and the threshold from which a proof is considered stuck are configurable with `TimeCleanupLockedProofs` and `GeneratingProofCleanupThreshold` respectively.

The `Generating` (`bool`) field has been refactored to `GeneratingSince` (`*time.Time`) to allow the time comparison against the `GeneratingProofCleanupThreshold` config value. If the field is `nil` it means that the proof is not currently being generating by a prover, otherwise we have the time in which the generation started.

Additional two fields have been added to the `Proof` struct: `CreatedAt` and `UpdatedAt`. For now they don't have a specific usecase, but the may come useful in debugging and troubleshooting.

Other stuff included:

- added UT in `state/pgstatestorage_test.go` for `CleanupLockedProofs`
- fixed `batchsender` script
- added Aggregator section in `config/config_test.go`
- Makefile `sail` and `resail` commands rebranded `ship` and `reship`
- cleaned up `go.sum` by running `go mod tidy -compat=1.17` (:warning: if we need to keep compatibility this can be reverted and run `go mod tidy -go=1.16 && go mod tidy -go=1.17` instead)

### Reviewers

Main reviewers:

@agnusmor 
@ToniRamirezM

### CODE REVIEW

**Review by ToniRamirezM — APPROVED** [review]

File: config/config_test.go [hunk 1]
```diff
@@ -305,7 +306,42 @@ func Test_Defaults(t *testing.T) {
...
+			path:          "Aggregator.TxProfitabilityMinReward",
+			expectedValue: aggregator.TokenAmountWithDecimals{Int: big.NewInt(1100000000000000000)},
+		},
+		{
+			path:          "Aggregator.ProofStatePollingInterval",
+			expectedValue: types.NewDuration(5 * time.Second),
+		},
+		{
+			path:          "Aggregator.CleanupLockedProofsInterval",
+			expectedValue: types.NewDuration(10 * time.Minute),
```
Comment (agnusmor) [inline config/config_test.go:339]: I think we can set CleanupLockedProofsInterval to 2 minutes and GeneratingProofCleanupThreshold to 10 minutes by default (for internal/public/main testnet). With these value in the worst scenario we will clean up a stucker proof in 12 minutes (from generating time). The provers used in production take less than 5-6 minutes to generate the batch proof (that is the most time consuming step).

On the other hand I see that we use "X * time.Second"  or "X * time.Minute to specify the interval value but in the case of the GeneratingProofCleanupThreshold we are using "30m", we do it by any reason? if not, to be consistent, I think we need to uses "30 * time.Minute". Anyway in my opinion is best to use the "30m" style for all the interval config values, but I think at least we need to specify the interval in the same way for all the config params.

If you agree with these values we need to change it also in the toml config file and in default.go file

Comment (kind84) [reply config/config_test.go]: @agnusmor I modified the config parameters according to your proposed values: 642ad61555b779d4bc154e1102834fa71c7a9652

About the difference that you found in `config/config_test.go`, please note that this is a test case asserting that the parameters are correctly parsed by the Go package (we use `github.com/spf13/viper`). It does that by calling `config.Load`: https://github.com/0xPolygonHermez/zkevm-node/blob/642ad61555b779d4bc154e1102834fa71c7a9652/config/config_test.go#L356

Hence the difference on the Go side: `CleanupLockedProofsInterval` is type `types.Duration` whereas `GeneratingProofCleanupThreshold` is type `string`. This because `GeneratingProofCleanupThreshold` is not directly used in the Go code, instead it is further parsed into Postgres `interval` type: https://github.com/0xPolygonHermez/zkevm-node/blob/642ad61555b779d4bc154e1102834fa71c7a9652/state/pgstatestorage.go#L1985-L1989

But on the `.toml` files both params follows the same syntax as you can see: https://github.com/0xPolygonHermez/zkevm-node/blob/642ad61555b779d4bc154e1102834fa71c7a9652/test/config/test.node.config.toml#L92-L93

**Review by agnusmor — APPROVED** [review]
